/* Maxima integration test file: "7 Inverse hyperbolic functions\7.2a Inverse hyperbolic tangent\7.2.4 x^m (c-a^2 c x^2)^p E^(n arctanh(a x)).mac" */

lst: '[

/* Integrands of the form x^m (c-a^2 c x^2)^p E^(n ArcTanh[a x]) */

/* Integrands of the form x^m (c-a^2 c x^2)^p E^(1 ArcTanh[a x]) */

/* Integrands of the form x^m E^ArcTanh[a x] (c-a^2 c x^2)^p */

/* p>0 */
[%e^atanh(a*x)*(c-a^2*c*x^2)^4,x,7,35/192*c^4*x*(1-a^2*x^2)^(3/2)+7/48*c^4*x*(1-a^2*x^2)^(5/2)+1/8*c^4*x*(1-a^2*x^2)^(7/2)-1/9*c^4*(1-a^2*x^2)^(9/2)/a+35/128*c^4*asin(a*x)/a+35/128*c^4*x*sqrt(1-a^2*x^2)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^3,x,6,5/24*c^3*x*(1-a^2*x^2)^(3/2)+1/6*c^3*x*(1-a^2*x^2)^(5/2)-1/7*c^3*(1-a^2*x^2)^(7/2)/a+5/16*c^3*asin(a*x)/a+5/16*c^3*x*sqrt(1-a^2*x^2)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^2,x,5,1/4*c^2*x*(1-a^2*x^2)^(3/2)-1/5*c^2*(1-a^2*x^2)^(5/2)/a+3/8*c^2*asin(a*x)/a+3/8*c^2*x*sqrt(1-a^2*x^2)],
[%e^atanh(a*x)*(c-a^2*c*x^2),x,4,-1/3*c*(1-a^2*x^2)^(3/2)/a+1/2*c*asin(a*x)/a+1/2*c*x*sqrt(1-a^2*x^2)],

/* p<0 */
[%e^atanh(a*x)*x^4/(c-a^2*c*x^2),x,5,-3/2*asin(a*x)/(a^5*c)+x^3*(1+a*x)/(a^2*c*sqrt(1-a^2*x^2))+4/3*x^2*sqrt(1-a^2*x^2)/(a^3*c)+1/6*(16+9*a*x)*sqrt(1-a^2*x^2)/(a^5*c)],
[%e^atanh(a*x)*x^3/(c-a^2*c*x^2),x,4,-3/2*asin(a*x)/(a^4*c)+x^2*(1+a*x)/(a^2*c*sqrt(1-a^2*x^2))+1/2*(4+3*a*x)*sqrt(1-a^2*x^2)/(a^4*c)],
[%e^atanh(a*x)*x^2/(c-a^2*c*x^2),x,5,-asin(a*x)/(a^3*c)+(1+a*x)/(a^3*c*sqrt(1-a^2*x^2))+sqrt(1-a^2*x^2)/(a^3*c)],
[%e^atanh(a*x)*x/(c-a^2*c*x^2),x,3,-asin(a*x)/(a^2*c)+(1+a*x)/(a^2*c*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(c-a^2*c*x^2),x,1,%e^atanh(a*x)/(a*c)],
[%e^atanh(a*x)/(x*(c-a^2*c*x^2)),x,6,-atanh(sqrt(1-a^2*x^2))/c+(1+a*x)/(c*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(x^2*(c-a^2*c*x^2)),x,6,-a*atanh(sqrt(1-a^2*x^2))/c+(1+a*x)/(c*x*sqrt(1-a^2*x^2))-2*sqrt(1-a^2*x^2)/(c*x)],
[%e^atanh(a*x)/(x^3*(c-a^2*c*x^2)),x,7,-3/2*a^2*atanh(sqrt(1-a^2*x^2))/c+(1+a*x)/(c*x^2*sqrt(1-a^2*x^2))-3/2*sqrt(1-a^2*x^2)/(c*x^2)-2*a*sqrt(1-a^2*x^2)/(c*x)],
[%e^atanh(a*x)/(x^4*(c-a^2*c*x^2)),x,8,-3/2*a^3*atanh(sqrt(1-a^2*x^2))/c+(1+a*x)/(c*x^3*sqrt(1-a^2*x^2))-4/3*sqrt(1-a^2*x^2)/(c*x^3)-3/2*a*sqrt(1-a^2*x^2)/(c*x^2)-8/3*a^2*sqrt(1-a^2*x^2)/(c*x)],
[%e^atanh(a*x)*x^6/(c-a^2*c*x^2)^2,x,6,1/3*x^5*(1+a*x)/(a^2*c^2*(1-a^2*x^2)^(3/2))+5/2*asin(a*x)/(a^7*c^2)-1/3*x^3*(5+6*a*x)/(a^4*c^2*sqrt(1-a^2*x^2))-8/3*x^2*sqrt(1-a^2*x^2)/(a^5*c^2)-1/6*(32+15*a*x)*sqrt(1-a^2*x^2)/(a^7*c^2)],
[%e^atanh(a*x)*x^5/(c-a^2*c*x^2)^2,x,5,1/3*x^4*(1+a*x)/(a^2*c^2*(1-a^2*x^2)^(3/2))+5/2*asin(a*x)/(a^6*c^2)-1/3*x^2*(4+5*a*x)/(a^4*c^2*sqrt(1-a^2*x^2))-1/6*(16+15*a*x)*sqrt(1-a^2*x^2)/(a^6*c^2)],
[%e^atanh(a*x)*x^4/(c-a^2*c*x^2)^2,x,5,1/3*x^3*(1+a*x)/(a^2*c^2*(1-a^2*x^2)^(3/2))+asin(a*x)/(a^5*c^2)-1/3*x*(3+4*a*x)/(a^4*c^2*sqrt(1-a^2*x^2))-8/3*sqrt(1-a^2*x^2)/(a^5*c^2)],
[%e^atanh(a*x)*x^3/(c-a^2*c*x^2)^2,x,4,1/3*x^2*(1+a*x)/(a^2*c^2*(1-a^2*x^2)^(3/2))+asin(a*x)/(a^4*c^2)+1/3*(-2-3*a*x)/(a^4*c^2*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x^2/(c-a^2*c*x^2)^2,x,4,1/3*x^2*(1+a*x)/(a*c^2*(1-a^2*x^2)^(3/2))+(-2/3)/(a^3*c^2*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x/(c-a^2*c*x^2)^2,x,3,1/3*(1+a*x)/(a^2*c^2*(1-a^2*x^2)^(3/2))-1/3*x/(a*c^2*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(c-a^2*c*x^2)^2,x,3,1/3*(1+a*x)/(a*c^2*(1-a^2*x^2)^(3/2))+2/3*x/(c^2*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(x*(c-a^2*c*x^2)^2),x,7,1/3*(1+a*x)/(c^2*(1-a^2*x^2)^(3/2))-atanh(sqrt(1-a^2*x^2))/c^2+1/3*(3+2*a*x)/(c^2*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(x^2*(c-a^2*c*x^2)^2),x,7,1/3*(1+a*x)/(c^2*x*(1-a^2*x^2)^(3/2))-a*atanh(sqrt(1-a^2*x^2))/c^2+1/3*(4+3*a*x)/(c^2*x*sqrt(1-a^2*x^2))-8/3*sqrt(1-a^2*x^2)/(c^2*x)],
[%e^atanh(a*x)/(x^3*(c-a^2*c*x^2)^2),x,8,1/3*(1+a*x)/(c^2*x^2*(1-a^2*x^2)^(3/2))-5/2*a^2*atanh(sqrt(1-a^2*x^2))/c^2+1/3*(5+4*a*x)/(c^2*x^2*sqrt(1-a^2*x^2))-5/2*sqrt(1-a^2*x^2)/(c^2*x^2)-8/3*a*sqrt(1-a^2*x^2)/(c^2*x)],
[%e^atanh(a*x)/(x^4*(c-a^2*c*x^2)^2),x,9,1/3*(1+a*x)/(c^2*x^3*(1-a^2*x^2)^(3/2))-5/2*a^3*atanh(sqrt(1-a^2*x^2))/c^2+1/3*(6+5*a*x)/(c^2*x^3*sqrt(1-a^2*x^2))-8/3*sqrt(1-a^2*x^2)/(c^2*x^3)-5/2*a*sqrt(1-a^2*x^2)/(c^2*x^2)-16/3*a^2*sqrt(1-a^2*x^2)/(c^2*x)],
[%e^atanh(a*x)*x^7/(c-a^2*c*x^2)^3,x,6,1/5*x^6*(1+a*x)/(a^2*c^3*(1-a^2*x^2)^(5/2))-1/15*x^4*(6+7*a*x)/(a^4*c^3*(1-a^2*x^2)^(3/2))-7/2*asin(a*x)/(a^8*c^3)+1/15*x^2*(24+35*a*x)/(a^6*c^3*sqrt(1-a^2*x^2))+1/10*(32+35*a*x)*sqrt(1-a^2*x^2)/(a^8*c^3)],
[%e^atanh(a*x)*x^6/(c-a^2*c*x^2)^3,x,6,1/5*x^5*(1+a*x)/(a^2*c^3*(1-a^2*x^2)^(5/2))-1/15*x^3*(5+6*a*x)/(a^4*c^3*(1-a^2*x^2)^(3/2))-asin(a*x)/(a^7*c^3)+1/5*x*(5+8*a*x)/(a^6*c^3*sqrt(1-a^2*x^2))+16/5*sqrt(1-a^2*x^2)/(a^7*c^3)],
[%e^atanh(a*x)*x^5/(c-a^2*c*x^2)^3,x,5,1/5*x^4*(1+a*x)/(a^2*c^3*(1-a^2*x^2)^(5/2))-1/15*x^2*(4+5*a*x)/(a^4*c^3*(1-a^2*x^2)^(3/2))-asin(a*x)/(a^6*c^3)+1/15*(8+15*a*x)/(a^6*c^3*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x^4/(c-a^2*c*x^2)^3,x,5,1/5*x^4*(1+a*x)/(a*c^3*(1-a^2*x^2)^(5/2))+(-4/15)/(a^5*c^3*(1-a^2*x^2)^(3/2))+4/5/(a^5*c^3*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x^3/(c-a^2*c*x^2)^3,x,4,1/5/(a^4*c^3*(1-a^2*x^2)^(5/2))+1/5*a*x^5/(c^3*(1-a^2*x^2)^(5/2))+(-1/3)/(a^4*c^3*(1-a^2*x^2)^(3/2)),1/5*x^2*(1+a*x)/(a^2*c^3*(1-a^2*x^2)^(5/2))+1/15*(-2-3*a*x)/(a^4*c^3*(1-a^2*x^2)^(3/2))+1/5*x/(a^3*c^3*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x^2/(c-a^2*c*x^2)^3,x,4,1/5*x^2*(1+a*x)/(a*c^3*(1-a^2*x^2)^(5/2))-2/15*(1-a*x)/(a^3*c^3*(1-a^2*x^2)^(3/2))-2/15*x/(a^2*c^3*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x/(c-a^2*c*x^2)^3,x,4,1/5*(1+a*x)/(a^2*c^3*(1-a^2*x^2)^(5/2))-1/15*x/(a*c^3*(1-a^2*x^2)^(3/2))-2/15*x/(a*c^3*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(c-a^2*c*x^2)^3,x,4,1/5*(1+a*x)/(a*c^3*(1-a^2*x^2)^(5/2))+4/15*x/(c^3*(1-a^2*x^2)^(3/2))+8/15*x/(c^3*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(x*(c-a^2*c*x^2)^3),x,8,1/5*(1+a*x)/(c^3*(1-a^2*x^2)^(5/2))+1/15*(5+4*a*x)/(c^3*(1-a^2*x^2)^(3/2))-atanh(sqrt(1-a^2*x^2))/c^3+1/15*(15+8*a*x)/(c^3*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(x^2*(c-a^2*c*x^2)^3),x,8,1/5*(1+a*x)/(c^3*x*(1-a^2*x^2)^(5/2))+1/15*(6+5*a*x)/(c^3*x*(1-a^2*x^2)^(3/2))-a*atanh(sqrt(1-a^2*x^2))/c^3+1/5*(8+5*a*x)/(c^3*x*sqrt(1-a^2*x^2))-16/5*sqrt(1-a^2*x^2)/(c^3*x)],
[%e^atanh(a*x)/(x^3*(c-a^2*c*x^2)^3),x,9,1/5*(1+a*x)/(c^3*x^2*(1-a^2*x^2)^(5/2))+1/15*(7+6*a*x)/(c^3*x^2*(1-a^2*x^2)^(3/2))-7/2*a^2*atanh(sqrt(1-a^2*x^2))/c^3+1/15*(35+24*a*x)/(c^3*x^2*sqrt(1-a^2*x^2))-7/2*sqrt(1-a^2*x^2)/(c^3*x^2)-16/5*a*sqrt(1-a^2*x^2)/(c^3*x)],
[%e^atanh(a*x)/(c-a^2*c*x^2)^4,x,5,1/7*(1+a*x)/(a*c^4*(1-a^2*x^2)^(7/2))+6/35*x/(c^4*(1-a^2*x^2)^(5/2))+8/35*x/(c^4*(1-a^2*x^2)^(3/2))+16/35*x/(c^4*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)/(c-a^2*c*x^2)^5,x,6,1/9*(1+a*x)/(a*c^5*(1-a^2*x^2)^(9/2))+8/63*x/(c^5*(1-a^2*x^2)^(7/2))+16/105*x/(c^5*(1-a^2*x^2)^(5/2))+64/315*x/(c^5*(1-a^2*x^2)^(3/2))+128/315*x/(c^5*sqrt(1-a^2*x^2))],

/* Integrands of the form x^m E^ArcTanh[a x] (1-a^2 x^2)^(p/2) */

/* p>0 */

/* p<0 */
[%e^atanh(a*x)*x^4/sqrt(1-a^2*x^2),x,3,-x/a^4-1/2*x^2/a^3-1/3*x^3/a^2-1/4*x^4/a-log(1-a*x)/a^5],
[%e^atanh(a*x)*x^3/sqrt(1-a^2*x^2),x,3,-x/a^3-1/2*x^2/a^2-1/3*x^3/a-log(1-a*x)/a^4],
[%e^atanh(a*x)*x^2/sqrt(1-a^2*x^2),x,3,-x/a^2-1/2*x^2/a-log(1-a*x)/a^3],
[%e^atanh(a*x)*x/sqrt(1-a^2*x^2),x,3,-x/a-log(1-a*x)/a^2],
[%e^atanh(a*x)/sqrt(1-a^2*x^2),x,2,-log(1-a*x)/a],
[%e^atanh(a*x)/(x*sqrt(1-a^2*x^2)),x,4,log(x)-log(1-a*x)],
[%e^atanh(a*x)/(x^2*sqrt(1-a^2*x^2)),x,3,(-1)/x+a*log(x)-a*log(1-a*x)],
[%e^atanh(a*x)/(x^3*sqrt(1-a^2*x^2)),x,3,(-1/2)/x^2-a/x+a^2*log(x)-a^2*log(1-a*x)],
[%e^atanh(a*x)/(x^4*sqrt(1-a^2*x^2)),x,3,(-1/3)/x^3-1/2*a/x^2-a^2/x+a^3*log(x)-a^3*log(1-a*x)],
[%e^atanh(a*x)*x^4/(1-a^2*x^2)^(3/2),x,3,x/a^4+1/2*x^2/a^3+1/2/(a^5*(1-a*x))+7/4*log(1-a*x)/a^5+1/4*log(1+a*x)/a^5],
[%e^atanh(a*x)*x^3/(1-a^2*x^2)^(3/2),x,3,x/a^3+1/2/(a^4*(1-a*x))+5/4*log(1-a*x)/a^4-1/4*log(1+a*x)/a^4],
[%e^atanh(a*x)*x^2/(1-a^2*x^2)^(3/2),x,3,1/2/(a^3*(1-a*x))+3/4*log(1-a*x)/a^3+1/4*log(1+a*x)/a^3],
[%e^atanh(a*x)*x/(1-a^2*x^2)^(3/2),x,4,1/2/(a^2*(1-a*x))-1/2*atanh(a*x)/a^2],
[%e^atanh(a*x)/(1-a^2*x^2)^(3/2),x,4,1/2/(a*(1-a*x))+1/2*atanh(a*x)/a],
[%e^atanh(a*x)/(x*(1-a^2*x^2)^(3/2)),x,3,1/2/(1-a*x)+log(x)-3/4*log(1-a*x)-1/4*log(1+a*x)],
[%e^atanh(a*x)/(x^2*(1-a^2*x^2)^(3/2)),x,3,(-1)/x+1/2*a/(1-a*x)+a*log(x)-5/4*a*log(1-a*x)+1/4*a*log(1+a*x)],
[%e^atanh(a*x)/(x^3*(1-a^2*x^2)^(3/2)),x,3,(-1/2)/x^2-a/x+1/2*a^2/(1-a*x)+2*a^2*log(x)-7/4*a^2*log(1-a*x)-1/4*a^2*log(1+a*x)],
[%e^atanh(a*x)/(x^4*(1-a^2*x^2)^(3/2)),x,3,(-1/3)/x^3-1/2*a/x^2-2*a^2/x+1/2*a^3/(1-a*x)+2*a^3*log(x)-9/4*a^3*log(1-a*x)+1/4*a^3*log(1+a*x)],
[%e^atanh(a*x)*x^6/(1-a^2*x^2)^(5/2),x,3,-x/a^6-1/2*x^2/a^5+1/8/(a^7*(1-a*x)^2)+(-5/4)/(a^7*(1-a*x))+(-1/8)/(a^7*(1+a*x))-39/16*log(1-a*x)/a^7-9/16*log(1+a*x)/a^7],
[%e^atanh(a*x)*x^5/(1-a^2*x^2)^(5/2),x,3,-x/a^5+1/8/(a^6*(1-a*x)^2)+(-1)/(a^6*(1-a*x))+1/8/(a^6*(1+a*x))-23/16*log(1-a*x)/a^6+7/16*log(1+a*x)/a^6],
[%e^atanh(a*x)*x^4/(1-a^2*x^2)^(5/2),x,3,1/8/(a^5*(1-a*x)^2)+(-3/4)/(a^5*(1-a*x))+(-1/8)/(a^5*(1+a*x))-11/16*log(1-a*x)/a^5-5/16*log(1+a*x)/a^5],
[%e^atanh(a*x)*x^3/(1-a^2*x^2)^(5/2),x,4,1/8/(a^4*(1-a*x)^2)+(-1/2)/(a^4*(1-a*x))+1/8/(a^4*(1+a*x))+3/8*atanh(a*x)/a^4],
[%e^atanh(a*x)*x^2/(1-a^2*x^2)^(5/2),x,4,1/8/(a^3*(1-a*x)^2)+(-1/4)/(a^3*(1-a*x))+(-1/8)/(a^3*(1+a*x))-1/8*atanh(a*x)/a^3],
[%e^atanh(a*x)*x/(1-a^2*x^2)^(5/2),x,4,1/8/(a^2*(1-a*x)^2)+1/8/(a^2*(1+a*x))-1/8*atanh(a*x)/a^2],
[%e^atanh(a*x)/(1-a^2*x^2)^(5/2),x,4,1/8/(a*(1-a*x)^2)+1/4/(a*(1-a*x))+(-1/8)/(a*(1+a*x))+3/8*atanh(a*x)/a],
[%e^atanh(a*x)/(x*(1-a^2*x^2)^(5/2)),x,3,1/8/(1-a*x)^2+1/2/(1-a*x)+1/8/(1+a*x)+log(x)-11/16*log(1-a*x)-5/16*log(1+a*x)],
[%e^atanh(a*x)/(x^2*(1-a^2*x^2)^(5/2)),x,3,(-1)/x+1/8*a/(1-a*x)^2+3/4*a/(1-a*x)-1/8*a/(1+a*x)+a*log(x)-23/16*a*log(1-a*x)+7/16*a*log(1+a*x)],
[%e^atanh(a*x)/(x^3*(1-a^2*x^2)^(5/2)),x,3,(-1/2)/x^2-a/x+1/8*a^2/(1-a*x)^2+a^2/(1-a*x)+1/8*a^2/(1+a*x)+3*a^2*log(x)-39/16*a^2*log(1-a*x)-9/16*a^2*log(1+a*x)],
[%e^atanh(a*x)/(x^4*(1-a^2*x^2)^(5/2)),x,3,(-1/3)/x^3-1/2*a/x^2-3*a^2/x+1/8*a^3/(1-a*x)^2+5/4*a^3/(1-a*x)-1/8*a^3/(1+a*x)+3*a^3*log(x)-59/16*a^3*log(1-a*x)+11/16*a^3*log(1+a*x)],

/* Integrands of the form x^m E^ArcTanh[a x] (c-a^2 c x^2)^(p/2) */

/* p>0 */
[%e^atanh(a*x)*x^2*(c-a^2*c*x^2)^(1/2),x,4,1/3*x^3*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+1/4*a*x^4*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^atanh(a*x)*x*(c-a^2*c*x^2)^(1/2),x,4,1/2*x^2*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+1/3*a*x^3*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^(1/2),x,3,x*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+1/2*a*x^2*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^(1/2)/x,x,4,a*x*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^(1/2)/x^2,x,4,-sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))+a*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^(3/2),x,4,2/3*c*(1+a*x)^3*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/4*c*(1+a*x)^4*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*(c-a^2*c*x^2)^(5/2),x,4,c^2*(1+a*x)^4*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-4/5*c^2*(1+a*x)^5*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+1/6*c^2*(1+a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*(c-a^2*c*x^2)^(7/2),x,4,8/5*c^3*(1+a*x)^5*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-2*c^3*(1+a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+6/7*c^3*(1+a*x)^7*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/8*c^3*(1+a*x)^8*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],

/* p<0 */
[%e^atanh(a*x)*x^4/sqrt(c-a^2*c*x^2),x,4,-x*sqrt(1-a^2*x^2)/(a^4*sqrt(c-a^2*c*x^2))-1/2*x^2*sqrt(1-a^2*x^2)/(a^3*sqrt(c-a^2*c*x^2))-1/3*x^3*sqrt(1-a^2*x^2)/(a^2*sqrt(c-a^2*c*x^2))-1/4*x^4*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))-log(1-a*x)*sqrt(1-a^2*x^2)/(a^5*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^3/sqrt(c-a^2*c*x^2),x,4,-x*sqrt(1-a^2*x^2)/(a^3*sqrt(c-a^2*c*x^2))-1/2*x^2*sqrt(1-a^2*x^2)/(a^2*sqrt(c-a^2*c*x^2))-1/3*x^3*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))-log(1-a*x)*sqrt(1-a^2*x^2)/(a^4*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^2/sqrt(c-a^2*c*x^2),x,4,-x*sqrt(1-a^2*x^2)/(a^2*sqrt(c-a^2*c*x^2))-1/2*x^2*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))-log(1-a*x)*sqrt(1-a^2*x^2)/(a^3*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x/sqrt(c-a^2*c*x^2),x,4,-x*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))-log(1-a*x)*sqrt(1-a^2*x^2)/(a^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/sqrt(c-a^2*c*x^2),x,3,-log(1-a*x)*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(x*sqrt(c-a^2*c*x^2)),x,5,log(x)*sqrt(1-a^2*x^2)/sqrt(c-a^2*c*x^2)-log(1-a*x)*sqrt(1-a^2*x^2)/sqrt(c-a^2*c*x^2)],
[%e^atanh(a*x)/(x^2*sqrt(c-a^2*c*x^2)),x,4,-sqrt(1-a^2*x^2)/(x*sqrt(c-a^2*c*x^2))+a*log(x)*sqrt(1-a^2*x^2)/sqrt(c-a^2*c*x^2)-a*log(1-a*x)*sqrt(1-a^2*x^2)/sqrt(c-a^2*c*x^2)],
[%e^atanh(a*x)/(x^3*sqrt(c-a^2*c*x^2)),x,4,-1/2*sqrt(1-a^2*x^2)/(x^2*sqrt(c-a^2*c*x^2))-a*sqrt(1-a^2*x^2)/(x*sqrt(c-a^2*c*x^2))+a^2*log(x)*sqrt(1-a^2*x^2)/sqrt(c-a^2*c*x^2)-a^2*log(1-a*x)*sqrt(1-a^2*x^2)/sqrt(c-a^2*c*x^2)],
[%e^atanh(a*x)/(x^4*sqrt(c-a^2*c*x^2)),x,4,-1/3*sqrt(1-a^2*x^2)/(x^3*sqrt(c-a^2*c*x^2))-1/2*a*sqrt(1-a^2*x^2)/(x^2*sqrt(c-a^2*c*x^2))-a^2*sqrt(1-a^2*x^2)/(x*sqrt(c-a^2*c*x^2))+a^3*log(x)*sqrt(1-a^2*x^2)/sqrt(c-a^2*c*x^2)-a^3*log(1-a*x)*sqrt(1-a^2*x^2)/sqrt(c-a^2*c*x^2)],
[%e^atanh(a*x)*x^5/(c-a^2*c*x^2)^(3/2),x,4,2*x*sqrt(1-a^2*x^2)/(a^5*c*sqrt(c-a^2*c*x^2))+1/2*x^2*sqrt(1-a^2*x^2)/(a^4*c*sqrt(c-a^2*c*x^2))+1/3*x^3*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))+1/2*sqrt(1-a^2*x^2)/(a^6*c*(1-a*x)*sqrt(c-a^2*c*x^2))+9/4*log(1-a*x)*sqrt(1-a^2*x^2)/(a^6*c*sqrt(c-a^2*c*x^2))-1/4*log(1+a*x)*sqrt(1-a^2*x^2)/(a^6*c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^4/(c-a^2*c*x^2)^(3/2),x,4,x*sqrt(1-a^2*x^2)/(a^4*c*sqrt(c-a^2*c*x^2))+1/2*x^2*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))+1/2*sqrt(1-a^2*x^2)/(a^5*c*(1-a*x)*sqrt(c-a^2*c*x^2))+7/4*log(1-a*x)*sqrt(1-a^2*x^2)/(a^5*c*sqrt(c-a^2*c*x^2))+1/4*log(1+a*x)*sqrt(1-a^2*x^2)/(a^5*c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^3/(c-a^2*c*x^2)^(3/2),x,4,x*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))+1/2*sqrt(1-a^2*x^2)/(a^4*c*(1-a*x)*sqrt(c-a^2*c*x^2))+5/4*log(1-a*x)*sqrt(1-a^2*x^2)/(a^4*c*sqrt(c-a^2*c*x^2))-1/4*log(1+a*x)*sqrt(1-a^2*x^2)/(a^4*c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^2/(c-a^2*c*x^2)^(3/2),x,4,1/2*sqrt(1-a^2*x^2)/(a^3*c*(1-a*x)*sqrt(c-a^2*c*x^2))+3/4*log(1-a*x)*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))+1/4*log(1+a*x)*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x/(c-a^2*c*x^2)^(3/2),x,5,1/2*sqrt(1-a^2*x^2)/(a^2*c*(1-a*x)*sqrt(c-a^2*c*x^2))-1/2*atanh(a*x)*sqrt(1-a^2*x^2)/(a^2*c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(c-a^2*c*x^2)^(3/2),x,5,1/2*sqrt(1-a^2*x^2)/(a*c*(1-a*x)*sqrt(c-a^2*c*x^2))+1/2*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(x*(c-a^2*c*x^2)^(3/2)),x,4,1/2*sqrt(1-a^2*x^2)/(c*(1-a*x)*sqrt(c-a^2*c*x^2))+log(x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))-3/4*log(1-a*x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))-1/4*log(1+a*x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(x^2*(c-a^2*c*x^2)^(3/2)),x,4,-sqrt(1-a^2*x^2)/(c*x*sqrt(c-a^2*c*x^2))+1/2*a*sqrt(1-a^2*x^2)/(c*(1-a*x)*sqrt(c-a^2*c*x^2))+a*log(x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))-5/4*a*log(1-a*x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))+1/4*a*log(1+a*x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(x^3*(c-a^2*c*x^2)^(3/2)),x,4,-1/2*sqrt(1-a^2*x^2)/(c*x^2*sqrt(c-a^2*c*x^2))-a*sqrt(1-a^2*x^2)/(c*x*sqrt(c-a^2*c*x^2))+1/2*a^2*sqrt(1-a^2*x^2)/(c*(1-a*x)*sqrt(c-a^2*c*x^2))+2*a^2*log(x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))-7/4*a^2*log(1-a*x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))-1/4*a^2*log(1+a*x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(x^4*(c-a^2*c*x^2)^(3/2)),x,4,-1/3*sqrt(1-a^2*x^2)/(c*x^3*sqrt(c-a^2*c*x^2))-1/2*a*sqrt(1-a^2*x^2)/(c*x^2*sqrt(c-a^2*c*x^2))-2*a^2*sqrt(1-a^2*x^2)/(c*x*sqrt(c-a^2*c*x^2))+1/2*a^3*sqrt(1-a^2*x^2)/(c*(1-a*x)*sqrt(c-a^2*c*x^2))+2*a^3*log(x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))-9/4*a^3*log(1-a*x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))+1/4*a^3*log(1+a*x)*sqrt(1-a^2*x^2)/(c*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^6/(c-a^2*c*x^2)^(5/2),x,4,-x*sqrt(1-a^2*x^2)/(a^6*c^2*sqrt(c-a^2*c*x^2))-1/2*x^2*sqrt(1-a^2*x^2)/(a^5*c^2*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a^7*c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))-5/4*sqrt(1-a^2*x^2)/(a^7*c^2*(1-a*x)*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a^7*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))-39/16*log(1-a*x)*sqrt(1-a^2*x^2)/(a^7*c^2*sqrt(c-a^2*c*x^2))-9/16*log(1+a*x)*sqrt(1-a^2*x^2)/(a^7*c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^5/(c-a^2*c*x^2)^(5/2),x,4,-x*sqrt(1-a^2*x^2)/(a^5*c^2*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a^6*c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))-sqrt(1-a^2*x^2)/(a^6*c^2*(1-a*x)*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a^6*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))-23/16*log(1-a*x)*sqrt(1-a^2*x^2)/(a^6*c^2*sqrt(c-a^2*c*x^2))+7/16*log(1+a*x)*sqrt(1-a^2*x^2)/(a^6*c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^4/(c-a^2*c*x^2)^(5/2),x,4,1/8*sqrt(1-a^2*x^2)/(a^5*c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))-3/4*sqrt(1-a^2*x^2)/(a^5*c^2*(1-a*x)*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a^5*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))-11/16*log(1-a*x)*sqrt(1-a^2*x^2)/(a^5*c^2*sqrt(c-a^2*c*x^2))-5/16*log(1+a*x)*sqrt(1-a^2*x^2)/(a^5*c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^3/(c-a^2*c*x^2)^(5/2),x,5,1/8*sqrt(1-a^2*x^2)/(a^4*c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))-1/2*sqrt(1-a^2*x^2)/(a^4*c^2*(1-a*x)*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a^4*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))+3/8*atanh(a*x)*sqrt(1-a^2*x^2)/(a^4*c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^2/(c-a^2*c*x^2)^(5/2),x,5,1/8*sqrt(1-a^2*x^2)/(a^3*c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))-1/4*sqrt(1-a^2*x^2)/(a^3*c^2*(1-a*x)*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a^3*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))-1/8*atanh(a*x)*sqrt(1-a^2*x^2)/(a^3*c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x/(c-a^2*c*x^2)^(5/2),x,5,1/8*sqrt(1-a^2*x^2)/(a^2*c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a^2*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))-1/8*atanh(a*x)*sqrt(1-a^2*x^2)/(a^2*c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(c-a^2*c*x^2)^(5/2),x,5,1/8*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))+1/4*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x)*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))+3/8*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(x*(c-a^2*c*x^2)^(5/2)),x,4,1/8*sqrt(1-a^2*x^2)/(c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))+1/2*sqrt(1-a^2*x^2)/(c^2*(1-a*x)*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(c^2*(1+a*x)*sqrt(c-a^2*c*x^2))+log(x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))-11/16*log(1-a*x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))-5/16*log(1+a*x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(x^2*(c-a^2*c*x^2)^(5/2)),x,4,-sqrt(1-a^2*x^2)/(c^2*x*sqrt(c-a^2*c*x^2))+1/8*a*sqrt(1-a^2*x^2)/(c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))+3/4*a*sqrt(1-a^2*x^2)/(c^2*(1-a*x)*sqrt(c-a^2*c*x^2))-1/8*a*sqrt(1-a^2*x^2)/(c^2*(1+a*x)*sqrt(c-a^2*c*x^2))+a*log(x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))-23/16*a*log(1-a*x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))+7/16*a*log(1+a*x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(x^3*(c-a^2*c*x^2)^(5/2)),x,4,-1/2*sqrt(1-a^2*x^2)/(c^2*x^2*sqrt(c-a^2*c*x^2))-a*sqrt(1-a^2*x^2)/(c^2*x*sqrt(c-a^2*c*x^2))+1/8*a^2*sqrt(1-a^2*x^2)/(c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))+a^2*sqrt(1-a^2*x^2)/(c^2*(1-a*x)*sqrt(c-a^2*c*x^2))+1/8*a^2*sqrt(1-a^2*x^2)/(c^2*(1+a*x)*sqrt(c-a^2*c*x^2))+3*a^2*log(x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))-39/16*a^2*log(1-a*x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))-9/16*a^2*log(1+a*x)*sqrt(1-a^2*x^2)/(c^2*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)/(c-a^2*c*x^2)^(7/2),x,5,1/24*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)^3*sqrt(c-a^2*c*x^2))+3/32*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)^2*sqrt(c-a^2*c*x^2))+3/16*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)*sqrt(c-a^2*c*x^2))-1/32*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)^2*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)*sqrt(c-a^2*c*x^2))+5/16*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c^3*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^ArcTanh[a x] (c-a^2 c x^2)^p with m symbolic */
[%e^atanh(a*x)*x^m*(c-a^2*c*x^2)^2,x,4,c^2*x^(1+m)*hypergeometric([-3/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)/(1+m)+a*c^2*x^(2+m)*hypergeometric([-3/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)/(2+m)],
[%e^atanh(a*x)*x^m*(c-a^2*c*x^2),x,4,c*x^(1+m)*hypergeometric([-1/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)/(1+m)+a*c*x^(2+m)*hypergeometric([-1/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)/(2+m)],
[%e^atanh(a*x)*x^m/(c-a^2*c*x^2),x,4,x^(1+m)*hypergeometric([3/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)/(c*(1+m))+a*x^(2+m)*hypergeometric([3/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)/(c*(2+m))],
[%e^atanh(a*x)*x^m/(c-a^2*c*x^2)^2,x,4,x^(1+m)*hypergeometric([5/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)/(c^2*(1+m))+a*x^(2+m)*hypergeometric([5/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)/(c^2*(2+m))],
[%e^atanh(a*x)*x^m/(c-a^2*c*x^2)^3,x,4,x^(1+m)*hypergeometric([7/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)/(c^3*(1+m))+a*x^(2+m)*hypergeometric([7/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)/(c^3*(2+m))],
[%e^atanh(a*x)*x^m*(1-a^2*x^2)^(5/2),x,3,x^(1+m)/(1+m)+a*x^(2+m)/(2+m)-2*a^2*x^(3+m)/(3+m)-2*a^3*x^(4+m)/(4+m)+a^4*x^(5+m)/(5+m)+a^5*x^(6+m)/(6+m)],
[%e^atanh(a*x)*x^m*(1-a^2*x^2)^(3/2),x,3,x^(1+m)/(1+m)+a*x^(2+m)/(2+m)-a^2*x^(3+m)/(3+m)-a^3*x^(4+m)/(4+m)],
[%e^atanh(a*x)*x^m*(1-a^2*x^2)^(1/2),x,3,x^(1+m)/(1+m)+a*x^(2+m)/(2+m)],
[%e^atanh(a*x)*x^m/(1-a^2*x^2)^(1/2),x,2,x^(1+m)*hypergeometric([1,1+m],[2+m],a*x)/(1+m)],
[%e^atanh(a*x)*x^m/(1-a^2*x^2)^(3/2),x,6,x^(1+m)*hypergeometric([2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)/(1+m)+a*x^(2+m)*hypergeometric([2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)/(2+m)],
[%e^atanh(a*x)*x^m/(1-a^2*x^2)^(5/2),x,6,x^(1+m)*hypergeometric([3,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)/(1+m)+a*x^(2+m)*hypergeometric([3,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)/(2+m)],
[%e^atanh(a*x)*x^m*(c-a^2*c*x^2)^(5/2),x,4,c^2*x^(1+m)*sqrt(c-a^2*c*x^2)/((1+m)*sqrt(1-a^2*x^2))+a*c^2*x^(2+m)*sqrt(c-a^2*c*x^2)/((2+m)*sqrt(1-a^2*x^2))-2*a^2*c^2*x^(3+m)*sqrt(c-a^2*c*x^2)/((3+m)*sqrt(1-a^2*x^2))-2*a^3*c^2*x^(4+m)*sqrt(c-a^2*c*x^2)/((4+m)*sqrt(1-a^2*x^2))+a^4*c^2*x^(5+m)*sqrt(c-a^2*c*x^2)/((5+m)*sqrt(1-a^2*x^2))+a^5*c^2*x^(6+m)*sqrt(c-a^2*c*x^2)/((6+m)*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x^m*(c-a^2*c*x^2)^(3/2),x,4,c*x^(1+m)*sqrt(c-a^2*c*x^2)/((1+m)*sqrt(1-a^2*x^2))+a*c*x^(2+m)*sqrt(c-a^2*c*x^2)/((2+m)*sqrt(1-a^2*x^2))-a^2*c*x^(3+m)*sqrt(c-a^2*c*x^2)/((3+m)*sqrt(1-a^2*x^2))-a^3*c*x^(4+m)*sqrt(c-a^2*c*x^2)/((4+m)*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x^m*(c-a^2*c*x^2)^(1/2),x,4,x^(1+m)*sqrt(c-a^2*c*x^2)/((1+m)*sqrt(1-a^2*x^2))+a*x^(2+m)*sqrt(c-a^2*c*x^2)/((2+m)*sqrt(1-a^2*x^2))],
[%e^atanh(a*x)*x^m/(c-a^2*c*x^2)^(1/2),x,3,x^(1+m)*hypergeometric([1,1+m],[2+m],a*x)*sqrt(1-a^2*x^2)/((1+m)*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^m/(c-a^2*c*x^2)^(3/2),x,7,x^(1+m)*hypergeometric([2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)*sqrt(1-a^2*x^2)/(c*(1+m)*sqrt(c-a^2*c*x^2))+a*x^(2+m)*hypergeometric([2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)*sqrt(1-a^2*x^2)/(c*(2+m)*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^m/(c-a^2*c*x^2)^(5/2),x,7,x^(1+m)*hypergeometric([3,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)*sqrt(1-a^2*x^2)/(c^2*(1+m)*sqrt(c-a^2*c*x^2))+a*x^(2+m)*hypergeometric([3,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)*sqrt(1-a^2*x^2)/(c^2*(2+m)*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^ArcTanh[a x] (c-a^2 c x^2)^p with p symbolic */
[%e^atanh(a*x)*x^m*(c-a^2*c*x^2)^p,x,5,x^(1+m)*(c-a^2*c*x^2)^p*hypergeometric([1/2*(1+m),1/2-p],[1/2*(3+m)],a^2*x^2)/((1+m)*(1-a^2*x^2)^p)+a*x^(2+m)*(c-a^2*c*x^2)^p*hypergeometric([1/2*(2+m),1/2-p],[1/2*(4+m)],a^2*x^2)/((2+m)*(1-a^2*x^2)^p)],
[%e^atanh(a*x)*x^3*(1-a^2*x^2)^p,x,6,-(1-a^2*x^2)^(1/2+p)/(a^4*(1+2*p))+(1-a^2*x^2)^(3/2+p)/(a^4*(3+2*p))+1/5*a*x^5*hypergeometric([5/2,1/2-p],[7/2],a^2*x^2)],
[%e^atanh(a*x)*x^2*(1-a^2*x^2)^p,x,6,-(1-a^2*x^2)^(1/2+p)/(a^3*(1+2*p))+(1-a^2*x^2)^(3/2+p)/(a^3*(3+2*p))+1/3*x^3*hypergeometric([3/2,1/2-p],[5/2],a^2*x^2)],
[%e^atanh(a*x)*x*(1-a^2*x^2)^p,x,4,-(1-a^2*x^2)^(1/2+p)/(a^2*(1+2*p))+1/3*a*x^3*hypergeometric([3/2,1/2-p],[5/2],a^2*x^2)],
[%e^atanh(a*x)*(1-a^2*x^2)^p,x,2,-2^(3/2+p)*(1-a*x)^(1/2+p)*hypergeometric([-1/2-p,1/2+p],[3/2+p],1/2*(1-a*x))/(a*(1+2*p))],
[%e^atanh(a*x)*(1-a^2*x^2)^p/x,x,5,a*x*hypergeometric([1/2,1/2-p],[3/2],a^2*x^2)-(1-a^2*x^2)^(1/2+p)*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)/(1+2*p)],
[%e^atanh(a*x)*(1-a^2*x^2)^p/x^2,x,5,-hypergeometric([-1/2,1/2-p],[1/2],a^2*x^2)/x-a*(1-a^2*x^2)^(1/2+p)*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)/(1+2*p)],
[%e^atanh(a*x)*(1-a^2*x^2)^p/x^3,x,5,-a*hypergeometric([-1/2,1/2-p],[1/2],a^2*x^2)/x-a^2*(1-a^2*x^2)^(1/2+p)*hypergeometric([2,1/2+p],[3/2+p],1-a^2*x^2)/(1+2*p)],
[%e^atanh(a*x)*x^3*(c-a^2*c*x^2)^p,x,7,(1-a^2*x^2)^(3/2)*(c-a^2*c*x^2)^p/(a^4*(3+2*p))+1/5*a*x^5*(c-a^2*c*x^2)^p*hypergeometric([5/2,1/2-p],[7/2],a^2*x^2)/(1-a^2*x^2)^p-(c-a^2*c*x^2)^p*sqrt(1-a^2*x^2)/(a^4*(1+2*p))],
[%e^atanh(a*x)*x^2*(c-a^2*c*x^2)^p,x,7,(1-a^2*x^2)^(3/2)*(c-a^2*c*x^2)^p/(a^3*(3+2*p))+1/3*x^3*(c-a^2*c*x^2)^p*hypergeometric([3/2,1/2-p],[5/2],a^2*x^2)/(1-a^2*x^2)^p-(c-a^2*c*x^2)^p*sqrt(1-a^2*x^2)/(a^3*(1+2*p))],
[%e^atanh(a*x)*x*(c-a^2*c*x^2)^p,x,5,1/3*a*x^3*(c-a^2*c*x^2)^p*hypergeometric([3/2,1/2-p],[5/2],a^2*x^2)/(1-a^2*x^2)^p-(c-a^2*c*x^2)^p*sqrt(1-a^2*x^2)/(a^2*(1+2*p))],
[%e^atanh(a*x)*(c-a^2*c*x^2)^p,x,3,-2^(3/2+p)*(1-a*x)^(1/2+p)*(c-a^2*c*x^2)^p*hypergeometric([-1/2-p,1/2+p],[3/2+p],1/2*(1-a*x))/(a*(1+2*p)*(1-a^2*x^2)^p)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^p/x,x,6,a*x*(c-a^2*c*x^2)^p*hypergeometric([1/2,1/2-p],[3/2],a^2*x^2)/(1-a^2*x^2)^p-(c-a^2*c*x^2)^p*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)*sqrt(1-a^2*x^2)/(1+2*p)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^p/x^2,x,6,-(c-a^2*c*x^2)^p*hypergeometric([-1/2,1/2-p],[1/2],a^2*x^2)/(x*(1-a^2*x^2)^p)-a*(c-a^2*c*x^2)^p*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)*sqrt(1-a^2*x^2)/(1+2*p)],
[%e^atanh(a*x)*(c-a^2*c*x^2)^p/x^3,x,6,-a*(c-a^2*c*x^2)^p*hypergeometric([-1/2,1/2-p],[1/2],a^2*x^2)/(x*(1-a^2*x^2)^p)-a^2*(c-a^2*c*x^2)^p*hypergeometric([2,1/2+p],[3/2+p],1-a^2*x^2)*sqrt(1-a^2*x^2)/(1+2*p)],

/* Integrands of the form x^m (c-a^2 c x^2)^p E^(2 ArcTanh[a x]) */

/* Integrands of the form x^m E^(2 ArcTanh[a x]) (c-a^2 c x^2)^p */

/* p>0 */
[%e^(2*atanh(a*x))*x^4*(c-a^2*c*x^2),x,3,1/5*c*x^5+1/3*a*c*x^6+1/7*a^2*c*x^7],
[%e^(2*atanh(a*x))*x^3*(c-a^2*c*x^2),x,3,1/4*c*x^4+2/5*a*c*x^5+1/6*a^2*c*x^6],
[%e^(2*atanh(a*x))*x^2*(c-a^2*c*x^2),x,3,1/3*c*x^3+1/2*a*c*x^4+1/5*a^2*c*x^5],
[%e^(2*atanh(a*x))*x*(c-a^2*c*x^2),x,3,1/2*c*x^2+2/3*a*c*x^3+1/4*a^2*c*x^4],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2),x,2,1/3*c*(1+a*x)^3/a],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)/x,x,3,2*a*c*x+1/2*a^2*c*x^2+c*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)/x^2,x,3,-c/x+a^2*c*x+2*a*c*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)/x^3,x,3,-1/2*c/x^2-2*a*c/x+a^2*c*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)/x^4,x,2,-1/3*c*(1+a*x)^3/x^3],
[%e^(2*atanh(a*x))*x^4*(c-a^2*c*x^2)^2,x,3,1/5*c^2*x^5+1/3*a*c^2*x^6-1/4*a^3*c^2*x^8-1/9*a^4*c^2*x^9],
[%e^(2*atanh(a*x))*x^3*(c-a^2*c*x^2)^2,x,3,1/4*c^2*x^4+2/5*a*c^2*x^5-2/7*a^3*c^2*x^7-1/8*a^4*c^2*x^8],
[%e^(2*atanh(a*x))*x^2*(c-a^2*c*x^2)^2,x,3,1/3*c^2*x^3+1/2*a*c^2*x^4-1/3*a^3*c^2*x^6-1/7*a^4*c^2*x^7],
[%e^(2*atanh(a*x))*x*(c-a^2*c*x^2)^2,x,3,1/2*c^2*x^2+2/3*a*c^2*x^3-2/5*a^3*c^2*x^5-1/6*a^4*c^2*x^6],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^2,x,3,1/2*c^2*(1+a*x)^4/a-1/5*c^2*(1+a*x)^5/a],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^2/x,x,3,2*a*c^2*x-2/3*a^3*c^2*x^3-1/4*a^4*c^2*x^4+c^2*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^2/x^2,x,3,-c^2/x-a^3*c^2*x^2-1/3*a^4*c^2*x^3+2*a*c^2*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^2/x^3,x,2,-1/2*c^2*(1+a*x)^4/x^2],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^2/x^4,x,3,-1/3*c^2/x^3-a*c^2/x^2-a^4*c^2*x-2*a^3*c^2*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^2/x^5,x,3,-1/4*c^2/x^4-2/3*a*c^2/x^3+2*a^3*c^2/x-a^4*c^2*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^2/x^6,x,3,-1/5*c^2/x^5-1/2*a*c^2/x^4+a^3*c^2/x^2+a^4*c^2/x],
[%e^(2*atanh(a*x))*x^4*(c-a^2*c*x^2)^3,x,3,1/5*c^3*x^5+1/3*a*c^3*x^6-1/7*a^2*c^3*x^7-1/2*a^3*c^3*x^8-1/9*a^4*c^3*x^9+1/5*a^5*c^3*x^10+1/11*a^6*c^3*x^11],
[%e^(2*atanh(a*x))*x^3*(c-a^2*c*x^2)^3,x,3,1/4*c^3*x^4+2/5*a*c^3*x^5-1/6*a^2*c^3*x^6-4/7*a^3*c^3*x^7-1/8*a^4*c^3*x^8+2/9*a^5*c^3*x^9+1/10*a^6*c^3*x^10],
[%e^(2*atanh(a*x))*x^2*(c-a^2*c*x^2)^3,x,3,4/5*c^3*(1+a*x)^5/a^3-2*c^3*(1+a*x)^6/a^3+13/7*c^3*(1+a*x)^7/a^3-3/4*c^3*(1+a*x)^8/a^3+1/9*c^3*(1+a*x)^9/a^3],
[%e^(2*atanh(a*x))*x*(c-a^2*c*x^2)^3,x,3,-4/5*c^3*(1+a*x)^5/a^2+4/3*c^3*(1+a*x)^6/a^2-5/7*c^3*(1+a*x)^7/a^2+1/8*c^3*(1+a*x)^8/a^2],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^3,x,3,4/5*c^3*(1+a*x)^5/a-2/3*c^3*(1+a*x)^6/a+1/7*c^3*(1+a*x)^7/a],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^3/x,x,3,2*a*c^3*x-1/2*a^2*c^3*x^2-4/3*a^3*c^3*x^3-1/4*a^4*c^3*x^4+2/5*a^5*c^3*x^5+1/6*a^6*c^3*x^6+c^3*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^3/x^2,x,3,-c^3/x-a^2*c^3*x-2*a^3*c^3*x^2-1/3*a^4*c^3*x^3+1/2*a^5*c^3*x^4+1/5*a^6*c^3*x^5+2*a*c^3*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^3/x^3,x,3,-1/2*c^3/x^2-2*a*c^3/x-4*a^3*c^3*x-1/2*a^4*c^3*x^2+2/3*a^5*c^3*x^3+1/4*a^6*c^3*x^4-a^2*c^3*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^3/x^4,x,3,-1/3*c^3/x^3-a*c^3/x^2+a^2*c^3/x-a^4*c^3*x+a^5*c^3*x^2+1/3*a^6*c^3*x^3-4*a^3*c^3*log(x)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^4,x,3,4/3*c^4*(1+a*x)^6/a-12/7*c^4*(1+a*x)^7/a+3/4*c^4*(1+a*x)^8/a-1/9*c^4*(1+a*x)^9/a],

/* p<0 */
[%e^(2*atanh(a*x))*x^4/(c-a^2*c*x^2),x,3,3*x/(a^4*c)+x^2/(a^3*c)+1/3*x^3/(a^2*c)+1/(a^5*c*(1-a*x))+4*log(1-a*x)/(a^5*c)],
[%e^(2*atanh(a*x))*x^3/(c-a^2*c*x^2),x,3,2*x/(a^3*c)+1/2*x^2/(a^2*c)+1/(a^4*c*(1-a*x))+3*log(1-a*x)/(a^4*c)],
[%e^(2*atanh(a*x))*x^2/(c-a^2*c*x^2),x,3,x/(a^2*c)+1/(a^3*c*(1-a*x))+2*log(1-a*x)/(a^3*c)],
[%e^(2*atanh(a*x))*x/(c-a^2*c*x^2),x,3,1/(a^2*c*(1-a*x))+log(1-a*x)/(a^2*c)],
[%e^(2*atanh(a*x))/(c-a^2*c*x^2),x,2,1/(a*c*(1-a*x))],
[%e^(2*atanh(a*x))/(x*(c-a^2*c*x^2)),x,3,1/(c*(1-a*x))+log(x)/c-log(1-a*x)/c],
[%e^(2*atanh(a*x))/(x^2*(c-a^2*c*x^2)),x,3,(-1)/(c*x)+a/(c*(1-a*x))+2*a*log(x)/c-2*a*log(1-a*x)/c],
[%e^(2*atanh(a*x))/(x^3*(c-a^2*c*x^2)),x,3,(-1/2)/(c*x^2)-2*a/(c*x)+a^2/(c*(1-a*x))+3*a^2*log(x)/c-3*a^2*log(1-a*x)/c],
[%e^(2*atanh(a*x))/(x^4*(c-a^2*c*x^2)),x,3,(-1/3)/(c*x^3)-a/(c*x^2)-3*a^2/(c*x)+a^3/(c*(1-a*x))+4*a^3*log(x)/c-4*a^3*log(1-a*x)/c],
[%e^(2*atanh(a*x))*x^4/(c-a^2*c*x^2)^2,x,3,-x/(a^4*c^2)+1/4/(a^5*c^2*(1-a*x)^2)+(-7/4)/(a^5*c^2*(1-a*x))-17/8*log(1-a*x)/(a^5*c^2)+1/8*log(1+a*x)/(a^5*c^2)],
[%e^(2*atanh(a*x))*x^3/(c-a^2*c*x^2)^2,x,3,1/4/(a^4*c^2*(1-a*x)^2)+(-5/4)/(a^4*c^2*(1-a*x))-7/8*log(1-a*x)/(a^4*c^2)-1/8*log(1+a*x)/(a^4*c^2)],
[%e^(2*atanh(a*x))*x^2/(c-a^2*c*x^2)^2,x,4,1/4/(a^3*c^2*(1-a*x)^2)+(-3/4)/(a^3*c^2*(1-a*x))+1/4*atanh(a*x)/(a^3*c^2)],
[%e^(2*atanh(a*x))*x/(c-a^2*c*x^2)^2,x,4,1/4/(a^2*c^2*(1-a*x)^2)+(-1/4)/(a^2*c^2*(1-a*x))-1/4*atanh(a*x)/(a^2*c^2)],
[%e^(2*atanh(a*x))/(c-a^2*c*x^2)^2,x,4,1/4/(a*c^2*(1-a*x)^2)+1/4/(a*c^2*(1-a*x))+1/4*atanh(a*x)/(a*c^2)],
[%e^(2*atanh(a*x))/(x*(c-a^2*c*x^2)^2),x,3,1/4/(c^2*(1-a*x)^2)+3/4/(c^2*(1-a*x))+log(x)/c^2-7/8*log(1-a*x)/c^2-1/8*log(1+a*x)/c^2],
[%e^(2*atanh(a*x))/(x^2*(c-a^2*c*x^2)^2),x,3,(-1)/(c^2*x)+1/4*a/(c^2*(1-a*x)^2)+5/4*a/(c^2*(1-a*x))+2*a*log(x)/c^2-17/8*a*log(1-a*x)/c^2+1/8*a*log(1+a*x)/c^2],
[%e^(2*atanh(a*x))/(x^3*(c-a^2*c*x^2)^2),x,3,(-1/2)/(c^2*x^2)-2*a/(c^2*x)+1/4*a^2/(c^2*(1-a*x)^2)+7/4*a^2/(c^2*(1-a*x))+4*a^2*log(x)/c^2-31/8*a^2*log(1-a*x)/c^2-1/8*a^2*log(1+a*x)/c^2],
[%e^(2*atanh(a*x))/(x^4*(c-a^2*c*x^2)^2),x,3,(-1/3)/(c^2*x^3)-a/(c^2*x^2)-4*a^2/(c^2*x)+1/4*a^3/(c^2*(1-a*x)^2)+9/4*a^3/(c^2*(1-a*x))+6*a^3*log(x)/c^2-49/8*a^3*log(1-a*x)/c^2+1/8*a^3*log(1+a*x)/c^2],
[%e^(2*atanh(a*x))*x^5/(c-a^2*c*x^2)^3,x,3,1/12/(a^6*c^3*(1-a*x)^3)+(-1/2)/(a^6*c^3*(1-a*x)^2)+23/16/(a^6*c^3*(1-a*x))+1/16/(a^6*c^3*(1+a*x))+13/16*log(1-a*x)/(a^6*c^3)+3/16*log(1+a*x)/(a^6*c^3)],
[%e^(2*atanh(a*x))*x^4/(c-a^2*c*x^2)^3,x,4,1/12/(a^5*c^3*(1-a*x)^3)+(-3/8)/(a^5*c^3*(1-a*x)^2)+11/16/(a^5*c^3*(1-a*x))+(-1/16)/(a^5*c^3*(1+a*x))-1/4*atanh(a*x)/(a^5*c^3)],
[%e^(2*atanh(a*x))*x^3/(c-a^2*c*x^2)^3,x,4,1/12/(a^4*c^3*(1-a*x)^3)+(-1/4)/(a^4*c^3*(1-a*x)^2)+3/16/(a^4*c^3*(1-a*x))+1/16/(a^4*c^3*(1+a*x))+1/8*atanh(a*x)/(a^4*c^3)],
[%e^(2*atanh(a*x))*x^2/(c-a^2*c*x^2)^3,x,2,1/6*(-1+2*a*x)/(a^3*c^3*(1-a*x)^3*(1+a*x))],
[%e^(2*atanh(a*x))*x/(c-a^2*c*x^2)^3,x,4,1/12/(a^2*c^3*(1-a*x)^3)+(-1/16)/(a^2*c^3*(1-a*x))+1/16/(a^2*c^3*(1+a*x))-1/8*atanh(a*x)/(a^2*c^3)],
[%e^(2*atanh(a*x))/(c-a^2*c*x^2)^3,x,4,1/12/(a*c^3*(1-a*x)^3)+1/8/(a*c^3*(1-a*x)^2)+3/16/(a*c^3*(1-a*x))+(-1/16)/(a*c^3*(1+a*x))+1/4*atanh(a*x)/(a*c^3)],
[%e^(2*atanh(a*x))/(x*(c-a^2*c*x^2)^3),x,3,1/12/(c^3*(1-a*x)^3)+1/4/(c^3*(1-a*x)^2)+11/16/(c^3*(1-a*x))+1/16/(c^3*(1+a*x))+log(x)/c^3-13/16*log(1-a*x)/c^3-3/16*log(1+a*x)/c^3],
[%e^(2*atanh(a*x))/(x^2*(c-a^2*c*x^2)^3),x,3,(-1)/(c^3*x)+1/12*a/(c^3*(1-a*x)^3)+3/8*a/(c^3*(1-a*x)^2)+23/16*a/(c^3*(1-a*x))-1/16*a/(c^3*(1+a*x))+2*a*log(x)/c^3-9/4*a*log(1-a*x)/c^3+1/4*a*log(1+a*x)/c^3],
[%e^(2*atanh(a*x))/(x^3*(c-a^2*c*x^2)^3),x,3,(-1/2)/(c^3*x^2)-2*a/(c^3*x)+1/12*a^2/(c^3*(1-a*x)^3)+1/2*a^2/(c^3*(1-a*x)^2)+39/16*a^2/(c^3*(1-a*x))+1/16*a^2/(c^3*(1+a*x))+5*a^2*log(x)/c^3-75/16*a^2*log(1-a*x)/c^3-5/16*a^2*log(1+a*x)/c^3],
[%e^(2*atanh(a*x))/(c-a^2*c*x^2)^4,x,4,1/32/(a*c^4*(1-a*x)^4)+1/16/(a*c^4*(1-a*x)^3)+3/32/(a*c^4*(1-a*x)^2)+5/32/(a*c^4*(1-a*x))+(-1/64)/(a*c^4*(1+a*x)^2)+(-5/64)/(a*c^4*(1+a*x))+15/64*atanh(a*x)/(a*c^4)],

/* Integrands of the form x^m E^(2 ArcTanh[a x]) (c-a^2 c x^2)^(p/2) */

/* p>0 */
[%e^(2*atanh(a*x))*x^3*(c-a^2*c*x^2)^(1/2),x,7,3/4*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)/a^4-3/5*x^2*sqrt(c-a^2*c*x^2)/a^2-1/2*x^3*sqrt(c-a^2*c*x^2)/a-1/5*x^4*sqrt(c-a^2*c*x^2)-3/20*(8+5*a*x)*sqrt(c-a^2*c*x^2)/a^4],
[%e^(2*atanh(a*x))*x^2*(c-a^2*c*x^2)^(1/2),x,6,7/8*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)/a^3-2/3*x^2*sqrt(c-a^2*c*x^2)/a-1/4*x^3*sqrt(c-a^2*c*x^2)-1/24*(32+21*a*x)*sqrt(c-a^2*c*x^2)/a^3],
[%e^(2*atanh(a*x))*x*(c-a^2*c*x^2)^(1/2),x,5,atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)/a^2-1/3*x^2*sqrt(c-a^2*c*x^2)-1/3*(5+3*a*x)*sqrt(c-a^2*c*x^2)/a^2],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(1/2),x,5,3/2*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)/a-3/2*sqrt(c-a^2*c*x^2)/a-1/2*(1+a*x)*sqrt(c-a^2*c*x^2)/a],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x,x,8,2*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)-atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x^2,x,8,a*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)-2*a*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-sqrt(c-a^2*c*x^2)/x],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x^3,x,6,-3/2*a^2*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-1/2*sqrt(c-a^2*c*x^2)/x^2-2*a*sqrt(c-a^2*c*x^2)/x],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x^4,x,7,-a^3*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-1/3*sqrt(c-a^2*c*x^2)/x^3-a*sqrt(c-a^2*c*x^2)/x^2-5/3*a^2*sqrt(c-a^2*c*x^2)/x],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x^5,x,8,-7/8*a^4*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-1/4*sqrt(c-a^2*c*x^2)/x^4-2/3*a*sqrt(c-a^2*c*x^2)/x^3-7/8*a^2*sqrt(c-a^2*c*x^2)/x^2-4/3*a^3*sqrt(c-a^2*c*x^2)/x],
[%e^(2*atanh(a*x))*x^3*(c-a^2*c*x^2)^(3/2),x,8,-11/35*x^2*(c-a^2*c*x^2)^(3/2)/a^2-1/3*x^3*(c-a^2*c*x^2)^(3/2)/a-1/7*x^4*(c-a^2*c*x^2)^(3/2)-1/420*(88+105*a*x)*(c-a^2*c*x^2)^(3/2)/a^4+1/8*c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a^4+1/8*c*x*sqrt(c-a^2*c*x^2)/a^3],
[%e^(2*atanh(a*x))*x^2*(c-a^2*c*x^2)^(3/2),x,7,-2/5*x^2*(c-a^2*c*x^2)^(3/2)/a-1/6*x^3*(c-a^2*c*x^2)^(3/2)-1/120*(32+45*a*x)*(c-a^2*c*x^2)^(3/2)/a^3+3/16*c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a^3+3/16*c*x*sqrt(c-a^2*c*x^2)/a^2],
[%e^(2*atanh(a*x))*x*(c-a^2*c*x^2)^(3/2),x,6,-1/5*x^2*(c-a^2*c*x^2)^(3/2)-1/30*(14+15*a*x)*(c-a^2*c*x^2)^(3/2)/a^2+1/4*c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a^2+1/4*c*x*sqrt(c-a^2*c*x^2)/a],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2),x,6,-5/12*(c-a^2*c*x^2)^(3/2)/a-1/4*(1+a*x)*(c-a^2*c*x^2)^(3/2)/a+5/8*c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a+5/8*c*x*sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)/x,x,9,-1/3*(c-a^2*c*x^2)^(3/2)+c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))-c^(3/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))+c*(1+a*x)*sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)/x^2,x,9,-(c-a^2*c*x^2)^(3/2)/x-1/2*a*c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))-2*a*c^(3/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))+1/2*a*c*(4-a*x)*sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)/x^3,x,9,-1/2*(c-a^2*c*x^2)^(3/2)/x^2-2*a^2*c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))-1/2*a^2*c^(3/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))-1/2*a*c*(4-a*x)*sqrt(c-a^2*c*x^2)/x],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)/x^4,x,9,-1/3*(c-a^2*c*x^2)^(3/2)/x^3-a^3*c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))+a^3*c^(3/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))-a*c*(1+a*x)*sqrt(c-a^2*c*x^2)/x^2],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)/x^5,x,7,-1/4*(c-a^2*c*x^2)^(3/2)/x^4-2/3*a*(c-a^2*c*x^2)^(3/2)/x^3+5/8*a^4*c^(3/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))-5/8*a^2*c*sqrt(c-a^2*c*x^2)/x^2],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)/x^6,x,8,-1/5*(c-a^2*c*x^2)^(3/2)/x^5-1/2*a*(c-a^2*c*x^2)^(3/2)/x^4-7/15*a^2*(c-a^2*c*x^2)^(3/2)/x^3+1/4*a^5*c^(3/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))-1/4*a^3*c*sqrt(c-a^2*c*x^2)/x^2],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)/x^7,x,9,-1/6*(c-a^2*c*x^2)^(3/2)/x^6-2/5*a*(c-a^2*c*x^2)^(3/2)/x^5-3/8*a^2*(c-a^2*c*x^2)^(3/2)/x^4-4/15*a^3*(c-a^2*c*x^2)^(3/2)/x^3+3/16*a^6*c^(3/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))-3/16*a^4*c*sqrt(c-a^2*c*x^2)/x^2],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)/x^8,x,10,-1/7*(c-a^2*c*x^2)^(3/2)/x^7-1/3*a*(c-a^2*c*x^2)^(3/2)/x^6-11/35*a^2*(c-a^2*c*x^2)^(3/2)/x^5-1/4*a^3*(c-a^2*c*x^2)^(3/2)/x^4-22/105*a^4*(c-a^2*c*x^2)^(3/2)/x^3+1/8*a^7*c^(3/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))-1/8*a^5*c*sqrt(c-a^2*c*x^2)/x^2],
[%e^(2*atanh(a*x))*x^3*(c-a^2*c*x^2)^(5/2),x,9,1/32*c*x*(c-a^2*c*x^2)^(3/2)/a^3-13/63*x^2*(c-a^2*c*x^2)^(5/2)/a^2-1/4*x^3*(c-a^2*c*x^2)^(5/2)/a-1/9*x^4*(c-a^2*c*x^2)^(5/2)-1/2520*(208+315*a*x)*(c-a^2*c*x^2)^(5/2)/a^4+3/64*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a^4+3/64*c^2*x*sqrt(c-a^2*c*x^2)/a^3],
[%e^(2*atanh(a*x))*x^2*(c-a^2*c*x^2)^(5/2),x,8,11/192*c*x*(c-a^2*c*x^2)^(3/2)/a^2-2/7*x^2*(c-a^2*c*x^2)^(5/2)/a-1/8*x^3*(c-a^2*c*x^2)^(5/2)-1/1680*(192+385*a*x)*(c-a^2*c*x^2)^(5/2)/a^3+11/128*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a^3+11/128*c^2*x*sqrt(c-a^2*c*x^2)/a^2],
[%e^(2*atanh(a*x))*x*(c-a^2*c*x^2)^(5/2),x,7,1/12*c*x*(c-a^2*c*x^2)^(3/2)/a-1/7*x^2*(c-a^2*c*x^2)^(5/2)-1/105*(27+35*a*x)*(c-a^2*c*x^2)^(5/2)/a^2+1/8*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a^2+1/8*c^2*x*sqrt(c-a^2*c*x^2)/a],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(5/2),x,7,7/24*c*x*(c-a^2*c*x^2)^(3/2)-7/30*(c-a^2*c*x^2)^(5/2)/a-1/6*(1+a*x)*(c-a^2*c*x^2)^(5/2)/a+7/16*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a+7/16*c^2*x*sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(5/2)/x,x,10,1/6*c*(2+3*a*x)*(c-a^2*c*x^2)^(3/2)-1/5*(c-a^2*c*x^2)^(5/2)+3/4*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))-c^(5/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))+1/4*c^2*(4+3*a*x)*sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(5/2)/x^2,x,10,1/12*a*c*(8-9*a*x)*(c-a^2*c*x^2)^(3/2)-(c-a^2*c*x^2)^(5/2)/x-9/8*a*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))-2*a*c^(5/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))+1/8*a*c^2*(16-9*a*x)*sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(5/2)/x^3,x,10,-1/6*a*c*(12+a*x)*(c-a^2*c*x^2)^(3/2)/x-1/2*(c-a^2*c*x^2)^(5/2)/x^2-3*a^2*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))+1/2*a^2*c^(5/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))-1/2*a^2*c^2*(1+6*a*x)*sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(5/2)/x^4,x,10,-1/6*a*c*(6-a*x)*(c-a^2*c*x^2)^(3/2)/x^2-1/3*(c-a^2*c*x^2)^(5/2)/x^3-1/2*a^3*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))+3*a^3*c^(5/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))-1/2*a^2*c^2*(1+6*a*x)*sqrt(c-a^2*c*x^2)/x],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(5/2)/x^5,x,10,-1/24*a*c*(16+9*a*x)*(c-a^2*c*x^2)^(3/2)/x^3-1/4*(c-a^2*c*x^2)^(5/2)/x^4+2*a^4*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))+9/8*a^4*c^(5/2)*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))+1/8*a^3*c^2*(16-9*a*x)*sqrt(c-a^2*c*x^2)/x],
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(7/2),x,8,15/64*c^2*x*(c-a^2*c*x^2)^(3/2)+3/16*c*x*(c-a^2*c*x^2)^(5/2)-9/56*(c-a^2*c*x^2)^(7/2)/a-1/8*(1+a*x)*(c-a^2*c*x^2)^(7/2)/a+45/128*c^(7/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a+45/128*c^3*x*sqrt(c-a^2*c*x^2)],

/* p<0 */
[%e^(2*atanh(a*x))*x^3/(c-a^2*c*x^2)^(1/2),x,7,-3*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/(a^4*sqrt(c))+(1+a*x)^2/(a^4*sqrt(c-a^2*c*x^2))+11/3*sqrt(c-a^2*c*x^2)/(a^4*c)+x*sqrt(c-a^2*c*x^2)/(a^3*c)+1/3*x^2*sqrt(c-a^2*c*x^2)/(a^2*c)],
[%e^(2*atanh(a*x))*x^2/(c-a^2*c*x^2)^(1/2),x,5,-5/2*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/(a^3*sqrt(c))+(1+a*x)^2/(a^3*sqrt(c-a^2*c*x^2))+1/2*(6+a*x)*sqrt(c-a^2*c*x^2)/(a^3*c)],
[%e^(2*atanh(a*x))*x/(c-a^2*c*x^2)^(1/2),x,5,-2*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/(a^2*sqrt(c))+(1+a*x)^2/(a^2*sqrt(c-a^2*c*x^2))+2*sqrt(c-a^2*c*x^2)/(a^2*c)],
[%e^(2*atanh(a*x))/(c-a^2*c*x^2)^(1/2),x,4,-atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/(a*sqrt(c))+2*(1+a*x)/(a*sqrt(c-a^2*c*x^2))],
[%e^(2*atanh(a*x))/(x*(c-a^2*c*x^2)^(1/2)),x,5,-atanh(sqrt(c-a^2*c*x^2)/sqrt(c))/sqrt(c)+2*(1+a*x)/sqrt(c-a^2*c*x^2)],
[%e^(2*atanh(a*x))/(x^2*(c-a^2*c*x^2)^(1/2)),x,6,-2*a*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))/sqrt(c)+2*a*(1+a*x)/sqrt(c-a^2*c*x^2)-sqrt(c-a^2*c*x^2)/(c*x)],
[%e^(2*atanh(a*x))/(x^3*(c-a^2*c*x^2)^(1/2)),x,7,-5/2*a^2*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))/sqrt(c)+2*a^2*(1+a*x)/sqrt(c-a^2*c*x^2)-1/2*sqrt(c-a^2*c*x^2)/(c*x^2)-2*a*sqrt(c-a^2*c*x^2)/(c*x)],
[%e^(2*atanh(a*x))/(x^4*(c-a^2*c*x^2)^(1/2)),x,8,-3*a^3*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))/sqrt(c)+2*a^3*(1+a*x)/sqrt(c-a^2*c*x^2)-1/3*sqrt(c-a^2*c*x^2)/(c*x^3)-a*sqrt(c-a^2*c*x^2)/(c*x^2)-8/3*a^2*sqrt(c-a^2*c*x^2)/(c*x)],
[%e^(2*atanh(a*x))*x^3/(c-a^2*c*x^2)^(3/2),x,6,1/3*(1+a*x)^2/(a^4*(c-a^2*c*x^2)^(3/2))+2*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/(a^4*c^(3/2))-8/3*(1+a*x)/(a^4*c*sqrt(c-a^2*c*x^2))-sqrt(c-a^2*c*x^2)/(a^4*c^2)],
[%e^(2*atanh(a*x))*x^2/(c-a^2*c*x^2)^(3/2),x,5,1/3*(1+a*x)^2/(a^3*(c-a^2*c*x^2)^(3/2))+atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/(a^3*c^(3/2))-5/3*(1+a*x)/(a^3*c*sqrt(c-a^2*c*x^2))],
[%e^(2*atanh(a*x))*x/(c-a^2*c*x^2)^(3/2),x,3,1/3*(1+a*x)^2/(a^2*(c-a^2*c*x^2)^(3/2))-2/3*(1+a*x)/(a^2*c*sqrt(c-a^2*c*x^2))],
[%e^(2*atanh(a*x))/(c-a^2*c*x^2)^(3/2),x,3,2/3*(1+a*x)/(a*(c-a^2*c*x^2)^(3/2))+1/3*x/(c*sqrt(c-a^2*c*x^2))],
[%e^(2*atanh(a*x))/(x*(c-a^2*c*x^2)^(3/2)),x,7,2/3*(1+a*x)/(c-a^2*c*x^2)^(3/2)-atanh(sqrt(c-a^2*c*x^2)/sqrt(c))/c^(3/2)+1/3*(3+4*a*x)/(c*sqrt(c-a^2*c*x^2))],
[%e^(2*atanh(a*x))/(x^2*(c-a^2*c*x^2)^(3/2)),x,7,2/3*a*(1+a*x)/(c-a^2*c*x^2)^(3/2)-2*a*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))/c^(3/2)+1/3*a*(6+7*a*x)/(c*sqrt(c-a^2*c*x^2))-sqrt(c-a^2*c*x^2)/(c^2*x)],
[%e^(2*atanh(a*x))/(x^3*(c-a^2*c*x^2)^(3/2)),x,8,2/3*a^2*(1+a*x)/(c-a^2*c*x^2)^(3/2)-7/2*a^2*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))/c^(3/2)+1/3*a^2*(9+10*a*x)/(c*sqrt(c-a^2*c*x^2))-1/2*sqrt(c-a^2*c*x^2)/(c^2*x^2)-2*a*sqrt(c-a^2*c*x^2)/(c^2*x)],
[%e^(2*atanh(a*x))/(c-a^2*c*x^2)^(5/2),x,4,2/5*(1+a*x)/(a*(c-a^2*c*x^2)^(5/2))+1/5*x/(c*(c-a^2*c*x^2)^(3/2))+2/5*x/(c^2*sqrt(c-a^2*c*x^2))],
[%e^(2*atanh(a*x))/(c-a^2*c*x^2)^(7/2),x,5,2/7*(1+a*x)/(a*(c-a^2*c*x^2)^(7/2))+1/7*x/(c*(c-a^2*c*x^2)^(5/2))+4/21*x/(c^2*(c-a^2*c*x^2)^(3/2))+8/21*x/(c^3*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^(2 ArcTanh[a x]) (c-a^2 c x^2)^p with m symbolic */
[%e^(2*atanh(a*x))*x^m*(c-a^2*c*x^2)^3,x,3,c^3*x^(1+m)/(1+m)+2*a*c^3*x^(2+m)/(2+m)-a^2*c^3*x^(3+m)/(3+m)-4*a^3*c^3*x^(4+m)/(4+m)-a^4*c^3*x^(5+m)/(5+m)+2*a^5*c^3*x^(6+m)/(6+m)+a^6*c^3*x^(7+m)/(7+m)],
[%e^(2*atanh(a*x))*x^m*(c-a^2*c*x^2)^2,x,3,c^2*x^(1+m)/(1+m)+2*a*c^2*x^(2+m)/(2+m)-2*a^3*c^2*x^(4+m)/(4+m)-a^4*c^2*x^(5+m)/(5+m)],
[%e^(2*atanh(a*x))*x^m*(c-a^2*c*x^2),x,3,c*x^(1+m)/(1+m)+2*a*c*x^(2+m)/(2+m)+a^2*c*x^(3+m)/(3+m)],
[%e^(2*atanh(a*x))*x^m/(c-a^2*c*x^2),x,2,x^(1+m)*hypergeometric([2,1+m],[2+m],a*x)/(c*(1+m))],
[%e^(2*atanh(a*x))*x^m/(c-a^2*c*x^2)^2,x,6,1/4*x^(1+m)/(c^2*(1-a*x)^2)+1/4*(2-m)*x^(1+m)/(c^2*(1-a*x))+1/8*x^(1+m)*hypergeometric([1,1+m],[2+m],-a*x)/(c^2*(1+m))+1/8*(1-4*m+2*m^2)*x^(1+m)*hypergeometric([1,1+m],[2+m],a*x)/(c^2*(1+m))],
[%e^(2*atanh(a*x))*x^m/(c-a^2*c*x^2)^3,x,8,-1/24*(2-m)*(4-m)*x^(1+m)/(c^3*(1+a*x))+1/6*x^(1+m)/(c^3*(1-a*x)^3*(1+a*x))+1/12*(4-m)*x^(1+m)/(c^3*(1-a*x)^2*(1+a*x))+1/24*(7-2*m)*(2-m)*x^(1+m)/(c^3*(1-a*x)*(1+a*x))+1/16*(2-m)*x^(1+m)*hypergeometric([1,1+m],[2+m],-a*x)/(c^3*(1+m))+1/48*(2-m)*(3-8*m+2*m^2)*x^(1+m)*hypergeometric([1,1+m],[2+m],a*x)/(c^3*(1+m))],
[%e^(2*atanh(a*x))*x^m*(c-a^2*c*x^2)^(5/2),x,7,-x^(1+m)*(c-a^2*c*x^2)^(5/2)/(6+m)+c^2*(7+2*m)*x^(1+m)*hypergeometric([-3/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)*sqrt(c-a^2*c*x^2)/((1+m)*(6+m)*sqrt(1-a^2*x^2))+2*a*c^2*x^(2+m)*hypergeometric([-3/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)*sqrt(c-a^2*c*x^2)/((2+m)*sqrt(1-a^2*x^2))],
[%e^(2*atanh(a*x))*x^m*(c-a^2*c*x^2)^(3/2),x,7,-x^(1+m)*(c-a^2*c*x^2)^(3/2)/(4+m)+c*(5+2*m)*x^(1+m)*hypergeometric([-1/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)*sqrt(c-a^2*c*x^2)/((1+m)*(4+m)*sqrt(1-a^2*x^2))+2*a*c*x^(2+m)*hypergeometric([-1/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)*sqrt(c-a^2*c*x^2)/((2+m)*sqrt(1-a^2*x^2))],
[%e^(2*atanh(a*x))*x^m*(c-a^2*c*x^2)^(1/2),x,7,c*(3+2*m)*x^(1+m)*hypergeometric([1/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)*sqrt(1-a^2*x^2)/((1+m)*(2+m)*sqrt(c-a^2*c*x^2))+2*a*c*x^(2+m)*hypergeometric([1/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)*sqrt(1-a^2*x^2)/((2+m)*sqrt(c-a^2*c*x^2))-x^(1+m)*sqrt(c-a^2*c*x^2)/(2+m)],
[%e^(2*atanh(a*x))*x^m/(c-a^2*c*x^2)^(1/2),x,7,2*x^(1+m)*(1+a*x)/sqrt(c-a^2*c*x^2)-(1+2*m)*x^(1+m)*hypergeometric([1/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)*sqrt(1-a^2*x^2)/((1+m)*sqrt(c-a^2*c*x^2))-2*a*(1+m)*x^(2+m)*hypergeometric([1/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)*sqrt(1-a^2*x^2)/((2+m)*sqrt(c-a^2*c*x^2))],
[%e^(2*atanh(a*x))*x^m/(c-a^2*c*x^2)^(3/2),x,7,2/3*x^(1+m)*(1+a*x)/(c-a^2*c*x^2)^(3/2)+1/3*(1-2*m)*x^(1+m)*hypergeometric([3/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)*sqrt(1-a^2*x^2)/(c*(1+m)*sqrt(c-a^2*c*x^2))+2/3*a*(1-m)*x^(2+m)*hypergeometric([3/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)*sqrt(1-a^2*x^2)/(c*(2+m)*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^(2 ArcTanh[a x]) (c-a^2 c x^2)^p with p symbolic */
[%e^(2*atanh(a*x))*(c-a^2*c*x^2)^p,x,3,-2^(1+p)*(c-a^2*c*x^2)^p*hypergeometric([-1-p,p],[1+p],1/2*(1-a*x))/(a*p*(1+a*x)^p)],

/* Integrands of the form x^m (c-a^2 c x^2)^p E^(3 ArcTanh[a x]) */

/* Integrands of the form x^m E^(3 ArcTanh[a x]) (c-a^2 c x^2)^p */

/* p>0 */
[%e^(3*atanh(a*x))*x^3*(c-a^2*c*x^2),x,7,23/16*c*asin(a*x)/a^4-17/15*c*x^2*sqrt(1-a^2*x^2)/a^2-23/24*c*x^3*sqrt(1-a^2*x^2)/a-3/5*c*x^4*sqrt(1-a^2*x^2)-1/6*a*c*x^5*sqrt(1-a^2*x^2)-1/240*c*(544+345*a*x)*sqrt(1-a^2*x^2)/a^4],
[%e^(3*atanh(a*x))*x^2*(c-a^2*c*x^2),x,6,13/8*c*asin(a*x)/a^3-19/15*c*x^2*sqrt(1-a^2*x^2)/a-3/4*c*x^3*sqrt(1-a^2*x^2)-1/5*a*c*x^4*sqrt(1-a^2*x^2)-1/120*c*(304+195*a*x)*sqrt(1-a^2*x^2)/a^3],
[%e^(3*atanh(a*x))*x*(c-a^2*c*x^2),x,6,15/8*c*asin(a*x)/a^2-15/8*c*sqrt(1-a^2*x^2)/a^2-5/8*c*(1+a*x)*sqrt(1-a^2*x^2)/a^2-1/4*c*(1+a*x)^2*sqrt(1-a^2*x^2)/a^2-1/4*c*(1+a*x)^3*sqrt(1-a^2*x^2)/a^2],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2),x,5,5/2*c*asin(a*x)/a-5/2*c*sqrt(1-a^2*x^2)/a-5/6*c*(1+a*x)*sqrt(1-a^2*x^2)/a-1/3*c*(1+a*x)^2*sqrt(1-a^2*x^2)/a],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)/x,x,8,7/2*c*asin(a*x)-c*atanh(sqrt(1-a^2*x^2))-3*c*sqrt(1-a^2*x^2)-1/2*a*c*x*sqrt(1-a^2*x^2)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)/x^2,x,8,3*a*c*asin(a*x)-3*a*c*atanh(sqrt(1-a^2*x^2))-a*c*sqrt(1-a^2*x^2)-c*sqrt(1-a^2*x^2)/x],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)/x^3,x,8,a^2*c*asin(a*x)-7/2*a^2*c*atanh(sqrt(1-a^2*x^2))-1/2*c*sqrt(1-a^2*x^2)/x^2-3*a*c*sqrt(1-a^2*x^2)/x],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)/x^4,x,7,-5/2*a^3*c*atanh(sqrt(1-a^2*x^2))-1/3*c*sqrt(1-a^2*x^2)/x^3-3/2*a*c*sqrt(1-a^2*x^2)/x^2-11/3*a^2*c*sqrt(1-a^2*x^2)/x],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)/x^5,x,8,-15/8*a^4*c*atanh(sqrt(1-a^2*x^2))-1/4*c*sqrt(1-a^2*x^2)/x^4-a*c*sqrt(1-a^2*x^2)/x^3-15/8*a^2*c*sqrt(1-a^2*x^2)/x^2-3*a^3*c*sqrt(1-a^2*x^2)/x],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)/x^6,x,9,-13/8*a^5*c*atanh(sqrt(1-a^2*x^2))-1/5*c*sqrt(1-a^2*x^2)/x^5-3/4*a*c*sqrt(1-a^2*x^2)/x^4-19/15*a^2*c*sqrt(1-a^2*x^2)/x^3-13/8*a^3*c*sqrt(1-a^2*x^2)/x^2-38/15*a^4*c*sqrt(1-a^2*x^2)/x],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^2,x,6,-7/12*c^2*(1-a^2*x^2)^(3/2)/a-7/20*c^2*(1+a*x)*(1-a^2*x^2)^(3/2)/a-1/5*c^2*(1+a*x)^2*(1-a^2*x^2)^(3/2)/a+7/8*c^2*asin(a*x)/a+7/8*c^2*x*sqrt(1-a^2*x^2)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^3,x,7,3/8*c^3*x*(1-a^2*x^2)^(3/2)-3/10*c^3*(1-a^2*x^2)^(5/2)/a-3/14*c^3*(1+a*x)*(1-a^2*x^2)^(5/2)/a-1/7*c^3*(1+a*x)^2*(1-a^2*x^2)^(5/2)/a+9/16*c^3*asin(a*x)/a+9/16*c^3*x*sqrt(1-a^2*x^2)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^4,x,8,55/192*c^4*x*(1-a^2*x^2)^(3/2)+11/48*c^4*x*(1-a^2*x^2)^(5/2)-11/56*c^4*(1-a^2*x^2)^(7/2)/a-11/72*c^4*(1+a*x)*(1-a^2*x^2)^(7/2)/a-1/9*c^4*(1+a*x)^2*(1-a^2*x^2)^(7/2)/a+55/128*c^4*asin(a*x)/a+55/128*c^4*x*sqrt(1-a^2*x^2)],

/* p<0 */
[%e^(3*atanh(a*x))*x^2/(c-a^2*c*x^2),x,6,1/3*(1+a*x)^3/(a^3*c*(1-a^2*x^2)^(3/2))+3*asin(a*x)/(a^3*c)-2*(1+a*x)^2/(a^3*c*sqrt(1-a^2*x^2))-3*sqrt(1-a^2*x^2)/(a^3*c)],
[%e^(3*atanh(a*x))*x/(c-a^2*c*x^2),x,4,1/3*(1+a*x)^3/(a^2*c*(1-a^2*x^2)^(3/2))+asin(a*x)/(a^2*c)-2*(1+a*x)/(a^2*c*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))/(c-a^2*c*x^2),x,1,1/3*%e^(3*atanh(a*x))/(a*c)],
[%e^(3*atanh(a*x))/(c-a^2*c*x^2)^2,x,5,1/5*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x)^3)+2/15*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x)^2)+2/15*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x))],
[%e^(3*atanh(a*x))/(c-a^2*c*x^2)^3,x,6,8/35*x/(c^3*sqrt(1-a^2*x^2))+1/7/(a*c^3*(1-a*x)^3*sqrt(1-a^2*x^2))+4/35/(a*c^3*(1-a*x)^2*sqrt(1-a^2*x^2))+4/35/(a*c^3*(1-a*x)*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))/(c-a^2*c*x^2)^4,x,7,8/63*x/(c^4*(1-a^2*x^2)^(3/2))+1/9/(a*c^4*(1-a*x)^3*(1-a^2*x^2)^(3/2))+2/21/(a*c^4*(1-a*x)^2*(1-a^2*x^2)^(3/2))+2/21/(a*c^4*(1-a*x)*(1-a^2*x^2)^(3/2))+16/63*x/(c^4*sqrt(1-a^2*x^2))],

/* Integrands of the form x^m E^(3 ArcTanh[a x]) (c-a^2 c x^2)^(p/2) */

/* p>0 */
[%e^(3*atanh(a*x))*x^3*(c-a^2*c*x^2)^(1/2),x,4,-4*x*sqrt(c-a^2*c*x^2)/(a^3*sqrt(1-a^2*x^2))-2*x^2*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))-4/3*x^3*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-3/4*x^4*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-1/5*a*x^5*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*log(1-a*x)*sqrt(c-a^2*c*x^2)/(a^4*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*x^2*(c-a^2*c*x^2)^(1/2),x,4,-4*x*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))-2*x^2*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-x^3*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-1/4*a*x^4*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*log(1-a*x)*sqrt(c-a^2*c*x^2)/(a^3*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*x*(c-a^2*c*x^2)^(1/2),x,4,-4*x*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-3/2*x^2*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-1/3*a*x^3*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*log(1-a*x)*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(1/2),x,4,-3*x*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-1/2*a*x^2*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*log(1-a*x)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x,x,4,-a*x*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*log(1-a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x^2,x,4,-sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))+3*a*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*a*log(1-a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x^3,x,4,-1/2*sqrt(c-a^2*c*x^2)/(x^2*sqrt(1-a^2*x^2))-3*a*sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))+4*a^2*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*a^2*log(1-a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x^4,x,4,-1/3*sqrt(c-a^2*c*x^2)/(x^3*sqrt(1-a^2*x^2))-3/2*a*sqrt(c-a^2*c*x^2)/(x^2*sqrt(1-a^2*x^2))-4*a^2*sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))+4*a^3*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*a^3*log(1-a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(1/2)/x^5,x,4,-1/4*sqrt(c-a^2*c*x^2)/(x^4*sqrt(1-a^2*x^2))-a*sqrt(c-a^2*c*x^2)/(x^3*sqrt(1-a^2*x^2))-2*a^2*sqrt(c-a^2*c*x^2)/(x^2*sqrt(1-a^2*x^2))-4*a^3*sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))+4*a^4*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*a^4*log(1-a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(3/2),x,3,1/4*c*(1+a*x)^4*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(5/2),x,4,2/5*c^2*(1+a*x)^5*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/6*c^2*(1+a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(7/2),x,4,2/3*c^3*(1+a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-4/7*c^3*(1+a*x)^7*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+1/8*c^3*(1+a*x)^8*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(9/2),x,4,8/7*c^4*(1+a*x)^7*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-3/2*c^4*(1+a*x)^8*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+2/3*c^4*(1+a*x)^9*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/10*c^4*(1+a*x)^10*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],

/* p<0 */
[%e^(3*atanh(a*x))/(c-a^2*c*x^2)^(1/2),x,4,2*sqrt(1-a^2*x^2)/(a*(1-a*x)*sqrt(c-a^2*c*x^2))+log(1-a*x)*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))],
[%e^(3*atanh(a*x))/(c-a^2*c*x^2)^(3/2),x,3,1/2*sqrt(1-a^2*x^2)/(a*c*(1-a*x)^2*sqrt(c-a^2*c*x^2))],
[%e^(3*atanh(a*x))/(c-a^2*c*x^2)^(5/2),x,5,1/6*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x)^3*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x)^2*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x)*sqrt(c-a^2*c*x^2))+1/8*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c^2*sqrt(c-a^2*c*x^2))],
[%e^(3*atanh(a*x))/(c-a^2*c*x^2)^(7/2),x,5,1/16*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)^4*sqrt(c-a^2*c*x^2))+1/12*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)^3*sqrt(c-a^2*c*x^2))+3/32*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)^2*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)*sqrt(c-a^2*c*x^2))-1/32*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)*sqrt(c-a^2*c*x^2))+5/32*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c^3*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^(3 ArcTanh[a x]) (c-a^2 c x^2)^p with m symbolic */
[%e^(3*atanh(a*x))*x^m*(c-a^2*c*x^2)^(1/2),x,5,-3*x^(1+m)*sqrt(c-a^2*c*x^2)/((1+m)*sqrt(1-a^2*x^2))-a*x^(2+m)*sqrt(c-a^2*c*x^2)/((2+m)*sqrt(1-a^2*x^2))+4*x^(1+m)*hypergeometric([1,1+m],[2+m],a*x)*sqrt(c-a^2*c*x^2)/((1+m)*sqrt(1-a^2*x^2))],

/* Integrands of the form x^m E^(3 ArcTanh[a x]) (c-a^2 c x^2)^p with p symbolic */
[%e^(3*atanh(a*x))*x^m*(c-a^2*c*x^2)^p,x,7,(3+4*m+2*p)*x^(1+m)*(c-a^2*c*x^2)^p*hypergeometric([1/2*(1+m),3/2-p],[1/2*(3+m)],a^2*x^2)/((1+m)*(m+2*p)*(1-a^2*x^2)^p)+a*(5+4*m+6*p)*x^(2+m)*(c-a^2*c*x^2)^p*hypergeometric([1/2*(2+m),3/2-p],[1/2*(4+m)],a^2*x^2)/((2+m)*(1+m+2*p)*(1-a^2*x^2)^p)-3*x^(1+m)*(c-a^2*c*x^2)^p/((m+2*p)*sqrt(1-a^2*x^2))-a*x^(2+m)*(c-a^2*c*x^2)^p/((1+m+2*p)*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*x^3*(c-a^2*c*x^2)^p,x,8,-3*(1-a^2*x^2)^(3/2)*(c-a^2*c*x^2)^p/(a^4*(3+2*p))+1/10*a*(17+6*p)*x^5*(c-a^2*c*x^2)^p*hypergeometric([5/2,3/2-p],[7/2],a^2*x^2)/((2+p)*(1-a^2*x^2)^p)+4*(c-a^2*c*x^2)^p/(a^4*(1-2*p)*sqrt(1-a^2*x^2))-1/2*a*x^5*(c-a^2*c*x^2)^p/((2+p)*sqrt(1-a^2*x^2))+7*(c-a^2*c*x^2)^p*sqrt(1-a^2*x^2)/(a^4*(1+2*p))],
[%e^(3*atanh(a*x))*x^2*(c-a^2*c*x^2)^p,x,8,-(1-a^2*x^2)^(3/2)*(c-a^2*c*x^2)^p/(a^3*(3+2*p))+1/6*(11+2*p)*x^3*(c-a^2*c*x^2)^p*hypergeometric([3/2,3/2-p],[5/2],a^2*x^2)/((1+p)*(1-a^2*x^2)^p)+4*(c-a^2*c*x^2)^p/(a^3*(1-2*p)*sqrt(1-a^2*x^2))-3/2*x^3*(c-a^2*c*x^2)^p/((1+p)*sqrt(1-a^2*x^2))+5*(c-a^2*c*x^2)^p*sqrt(1-a^2*x^2)/(a^3*(1+2*p))],
[%e^(3*atanh(a*x))*x*(c-a^2*c*x^2)^p,x,5,3*2^(3/2+p)*(1-a*x)^(-1/2+p)*(c-a^2*c*x^2)^p*hypergeometric([-3/2-p,-1/2+p],[1/2+p],1/2*(1-a*x))/(a^2*(1-p-2*p^2)*(1-a^2*x^2)^p)-1/2*(1+a*x)^3*(c-a^2*c*x^2)^p/(a^2*(1+p)*sqrt(1-a^2*x^2))],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^p,x,3,2^(5/2+p)*(1-a*x)^(-1/2+p)*(c-a^2*c*x^2)^p*hypergeometric([-3/2-p,-1/2+p],[1/2+p],1/2*(1-a*x))/(a*(1-2*p)*(1-a^2*x^2)^p)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^p/x,x,8,1/2*a*(1+6*p)*x*(c-a^2*c*x^2)^p*hypergeometric([1/2,3/2-p],[3/2],a^2*x^2)/(p*(1-a^2*x^2)^p)+4*(c-a^2*c*x^2)^p/((1-2*p)*sqrt(1-a^2*x^2))-1/2*a*x*(c-a^2*c*x^2)^p/(p*sqrt(1-a^2*x^2))-(c-a^2*c*x^2)^p*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)*sqrt(1-a^2*x^2)/(1+2*p)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^p/x^2,x,9,a^2*(5-2*p)*x*(c-a^2*c*x^2)^p*hypergeometric([1/2,3/2-p],[3/2],a^2*x^2)/(1-a^2*x^2)^p+4*a*(c-a^2*c*x^2)^p/((1-2*p)*sqrt(1-a^2*x^2))-(c-a^2*c*x^2)^p/(x*sqrt(1-a^2*x^2))-3*a*(c-a^2*c*x^2)^p*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)*sqrt(1-a^2*x^2)/(1+2*p)],
[%e^(3*atanh(a*x))*(c-a^2*c*x^2)^p/x^3,x,8,a^3*(7-6*p)*x*(c-a^2*c*x^2)^p*hypergeometric([1/2,3/2-p],[3/2],a^2*x^2)/(1-a^2*x^2)^p-1/2*(c-a^2*c*x^2)^p/(x^2*sqrt(1-a^2*x^2))-3*a*(c-a^2*c*x^2)^p/(x*sqrt(1-a^2*x^2))+1/2*a^2*(9-2*p)*(c-a^2*c*x^2)^p*hypergeometric([1,-1/2+p],[1/2+p],1-a^2*x^2)/((1-2*p)*sqrt(1-a^2*x^2))],

/* Integrands of the form x^m (c-a^2 c x^2)^p E^(4 ArcTanh[a x]) */

/* Integrands of the form x^m E^(4 ArcTanh[a x]) (c-a^2 c x^2)^p */

/* p>0 */
[%e^(4*atanh(a*x))*(c-a^2*c*x^2)^5,x,3,c^5*(1+a*x)^8/a-4/3*c^5*(1+a*x)^9/a+3/5*c^5*(1+a*x)^10/a-1/11*c^5*(1+a*x)^11/a],
[%e^(4*atanh(a*x))*(c-a^2*c*x^2)^4,x,3,4/7*c^4*(1+a*x)^7/a-1/2*c^4*(1+a*x)^8/a+1/9*c^4*(1+a*x)^9/a],
[%e^(4*atanh(a*x))*(c-a^2*c*x^2)^3,x,3,1/3*c^3*(1+a*x)^6/a-1/7*c^3*(1+a*x)^7/a],
[%e^(4*atanh(a*x))*(c-a^2*c*x^2)^2,x,2,1/5*c^2*(1+a*x)^5/a],
[%e^(4*atanh(a*x))*(c-a^2*c*x^2),x,3,-7*c*x-2*a*c*x^2-1/3*a^2*c*x^3-8*c*log(1-a*x)/a,-4*c*x-c*(1+a*x)^2/a-1/3*c*(1+a*x)^3/a-8*c*log(1-a*x)/a],

/* p<0 */
[%e^(4*atanh(a*x))/(c-a^2*c*x^2),x,2,x/(c*(1-a*x)^2)],
[%e^(4*atanh(a*x))/(c-a^2*c*x^2)^2,x,2,1/3/(a*c^2*(1-a*x)^3)],
[%e^(4*atanh(a*x))/(c-a^2*c*x^2)^3,x,4,1/8/(a*c^3*(1-a*x)^4)+1/12/(a*c^3*(1-a*x)^3)+1/16/(a*c^3*(1-a*x)^2)+1/16/(a*c^3*(1-a*x))+1/16*atanh(a*x)/(a*c^3)],
[%e^(4*atanh(a*x))/(c-a^2*c*x^2)^4,x,4,1/20/(a*c^4*(1-a*x)^5)+1/16/(a*c^4*(1-a*x)^4)+1/16/(a*c^4*(1-a*x)^3)+1/16/(a*c^4*(1-a*x)^2)+5/64/(a*c^4*(1-a*x))+(-1/64)/(a*c^4*(1+a*x))+3/32*atanh(a*x)/(a*c^4)],

/* Integrands of the form x^m E^(4 ArcTanh[a x]) (c-a^2 c x^2)^(p/2) */

/* p>0 */

/* p<0 */

/* Integrands of the form x^m E^(4 ArcTanh[a x]) (c-a^2 c x^2)^p with p symbolic */
[%e^(4*atanh(a*x))*(c-a^2*c*x^2)^p,x,3,2^(2+p)*c*(1+a*x)^(1-p)*(c-a^2*c*x^2)^(-1+p)*hypergeometric([-2-p,-1+p],[p],1/2*(1-a*x))/(a*(1-p))],

/* Integrands of the form x^m (c-a^2 c x^2)^p / E^(1 ArcTanh[a x]) */

/* Integrands of the form x^m E^(-ArcTanh[a x]) (c-a^2 c x^2)^p */

/* p>0 */
[(c-a^2*c*x^2)^4/%e^atanh(a*x),x,7,35/192*c^4*x*(1-a^2*x^2)^(3/2)+7/48*c^4*x*(1-a^2*x^2)^(5/2)+1/8*c^4*x*(1-a^2*x^2)^(7/2)+1/9*c^4*(1-a^2*x^2)^(9/2)/a+35/128*c^4*asin(a*x)/a+35/128*c^4*x*sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^3/%e^atanh(a*x),x,6,5/24*c^3*x*(1-a^2*x^2)^(3/2)+1/6*c^3*x*(1-a^2*x^2)^(5/2)+1/7*c^3*(1-a^2*x^2)^(7/2)/a+5/16*c^3*asin(a*x)/a+5/16*c^3*x*sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^2/%e^atanh(a*x),x,5,1/4*c^2*x*(1-a^2*x^2)^(3/2)+1/5*c^2*(1-a^2*x^2)^(5/2)/a+3/8*c^2*asin(a*x)/a+3/8*c^2*x*sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)/%e^atanh(a*x),x,4,1/3*c*(1-a^2*x^2)^(3/2)/a+1/2*c*asin(a*x)/a+1/2*c*x*sqrt(1-a^2*x^2)],

/* p<0 */
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)),x,1,(-1)/(%e^atanh(a*x)*a*c)],
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)^2),x,3,1/3*(-1+a*x)/(a*c^2*(1-a^2*x^2)^(3/2))+2/3*x/(c^2*sqrt(1-a^2*x^2))],
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)^3),x,4,1/5*(-1+a*x)/(a*c^3*(1-a^2*x^2)^(5/2))+4/15*x/(c^3*(1-a^2*x^2)^(3/2))+8/15*x/(c^3*sqrt(1-a^2*x^2))],
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)^4),x,5,1/7*(-1+a*x)/(a*c^4*(1-a^2*x^2)^(7/2))+6/35*x/(c^4*(1-a^2*x^2)^(5/2))+8/35*x/(c^4*(1-a^2*x^2)^(3/2))+16/35*x/(c^4*sqrt(1-a^2*x^2))],
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)^5),x,6,1/9*(-1+a*x)/(a*c^5*(1-a^2*x^2)^(9/2))+8/63*x/(c^5*(1-a^2*x^2)^(7/2))+16/105*x/(c^5*(1-a^2*x^2)^(5/2))+64/315*x/(c^5*(1-a^2*x^2)^(3/2))+128/315*x/(c^5*sqrt(1-a^2*x^2))],

/* Integrands of the form x^m E^(-ArcTanh[a x]) (c-a^2 c x^2)^(p/2) */

/* p>0 */
[x^m*(c-a^2*c*x^2)^(1/2)/%e^atanh(a*x),x,4,x^(1+m)*sqrt(c-a^2*c*x^2)/((1+m)*sqrt(1-a^2*x^2))-a*x^(2+m)*sqrt(c-a^2*c*x^2)/((2+m)*sqrt(1-a^2*x^2))],
[x^2*(c-a^2*c*x^2)^(1/2)/%e^atanh(a*x),x,4,1/3*x^3*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-1/4*a*x^4*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[x*(c-a^2*c*x^2)^(1/2)/%e^atanh(a*x),x,4,1/2*x^2*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-1/3*a*x^3*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(1/2)/%e^atanh(a*x),x,3,x*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-1/2*a*x^2*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(1/2)/(%e^atanh(a*x)*x),x,4,-a*x*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(1/2)/(%e^atanh(a*x)*x^2),x,4,-sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))-a*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(3/2)/%e^atanh(a*x),x,4,-2/3*c*(1-a*x)^3*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+1/4*c*(1-a*x)^4*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[(c-a^2*c*x^2)^(5/2)/%e^atanh(a*x),x,4,-c^2*(1-a*x)^4*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+4/5*c^2*(1-a*x)^5*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/6*c^2*(1-a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[(c-a^2*c*x^2)^(7/2)/%e^atanh(a*x),x,4,-8/5*c^3*(1-a*x)^5*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+2*c^3*(1-a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-6/7*c^3*(1-a*x)^7*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+1/8*c^3*(1-a*x)^8*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[(c-a^2*c*x^2)^(9/2)/%e^atanh(a*x),x,4,-8/3*c^4*(1-a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+32/7*c^4*(1-a*x)^7*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-3*c^4*(1-a*x)^8*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+8/9*c^4*(1-a*x)^9*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/10*c^4*(1-a*x)^10*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],

/* p<0 */
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)^(1/2)),x,3,log(1+a*x)*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))],
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)^(3/2)),x,5,-1/2*sqrt(1-a^2*x^2)/(a*c*(1+a*x)*sqrt(c-a^2*c*x^2))+1/2*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c*sqrt(c-a^2*c*x^2))],
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)^(5/2)),x,5,1/8*sqrt(1-a^2*x^2)/(a*c^2*(1-a*x)*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x)^2*sqrt(c-a^2*c*x^2))-1/4*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))+3/8*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c^2*sqrt(c-a^2*c*x^2))],
[1/(%e^atanh(a*x)*(c-a^2*c*x^2)^(7/2)),x,5,1/32*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)^2*sqrt(c-a^2*c*x^2))+1/8*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)*sqrt(c-a^2*c*x^2))-1/24*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)^3*sqrt(c-a^2*c*x^2))-3/32*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)^2*sqrt(c-a^2*c*x^2))-3/16*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)*sqrt(c-a^2*c*x^2))+5/16*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c^3*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^(-ArcTanh[a x]) (c-a^2 c x^2)^p with p symbolic */
[x^m*(c-a^2*c*x^2)^p/%e^atanh(a*x),x,5,x^(1+m)*(c-a^2*c*x^2)^p*hypergeometric([1/2*(1+m),1/2-p],[1/2*(3+m)],a^2*x^2)/((1+m)*(1-a^2*x^2)^p)-a*x^(2+m)*(c-a^2*c*x^2)^p*hypergeometric([1/2*(2+m),1/2-p],[1/2*(4+m)],a^2*x^2)/((2+m)*(1-a^2*x^2)^p)],
[x^3*(1-a^2*x^2)^p/%e^atanh(a*x),x,6,-(1-a^2*x^2)^(1/2+p)/(a^4*(1+2*p))+(1-a^2*x^2)^(3/2+p)/(a^4*(3+2*p))-1/5*a*x^5*hypergeometric([5/2,1/2-p],[7/2],a^2*x^2)],
[x^2*(1-a^2*x^2)^p/%e^atanh(a*x),x,6,(1-a^2*x^2)^(1/2+p)/(a^3*(1+2*p))-(1-a^2*x^2)^(3/2+p)/(a^3*(3+2*p))+1/3*x^3*hypergeometric([3/2,1/2-p],[5/2],a^2*x^2)],
[x*(1-a^2*x^2)^p/%e^atanh(a*x),x,4,-(1-a^2*x^2)^(1/2+p)/(a^2*(1+2*p))-1/3*a*x^3*hypergeometric([3/2,1/2-p],[5/2],a^2*x^2)],
[(1-a^2*x^2)^p/%e^atanh(a*x),x,2,-2^(1/2+p)*(1-a*x)^(3/2+p)*hypergeometric([1/2-p,3/2+p],[5/2+p],1/2*(1-a*x))/(a*(3+2*p))],
[(1-a^2*x^2)^p/(%e^atanh(a*x)*x),x,5,-a*x*hypergeometric([1/2,1/2-p],[3/2],a^2*x^2)-(1-a^2*x^2)^(1/2+p)*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)/(1+2*p)],
[(1-a^2*x^2)^p/(%e^atanh(a*x)*x^2),x,5,-hypergeometric([-1/2,1/2-p],[1/2],a^2*x^2)/x+a*(1-a^2*x^2)^(1/2+p)*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)/(1+2*p)],
[x^3*(c-a^2*c*x^2)^p/%e^atanh(a*x),x,7,(1-a^2*x^2)^(3/2)*(c-a^2*c*x^2)^p/(a^4*(3+2*p))-1/5*a*x^5*(c-a^2*c*x^2)^p*hypergeometric([5/2,1/2-p],[7/2],a^2*x^2)/(1-a^2*x^2)^p-(c-a^2*c*x^2)^p*sqrt(1-a^2*x^2)/(a^4*(1+2*p))],
[x^2*(c-a^2*c*x^2)^p/%e^atanh(a*x),x,7,-(1-a^2*x^2)^(3/2)*(c-a^2*c*x^2)^p/(a^3*(3+2*p))+1/3*x^3*(c-a^2*c*x^2)^p*hypergeometric([3/2,1/2-p],[5/2],a^2*x^2)/(1-a^2*x^2)^p+(c-a^2*c*x^2)^p*sqrt(1-a^2*x^2)/(a^3*(1+2*p))],
[x*(c-a^2*c*x^2)^p/%e^atanh(a*x),x,5,-1/3*a*x^3*(c-a^2*c*x^2)^p*hypergeometric([3/2,1/2-p],[5/2],a^2*x^2)/(1-a^2*x^2)^p-(c-a^2*c*x^2)^p*sqrt(1-a^2*x^2)/(a^2*(1+2*p))],
[(c-a^2*c*x^2)^p/%e^atanh(a*x),x,3,-2^(1/2+p)*(1-a*x)^(3/2+p)*(c-a^2*c*x^2)^p*hypergeometric([1/2-p,3/2+p],[5/2+p],1/2*(1-a*x))/(a*(3+2*p)*(1-a^2*x^2)^p)],
[(c-a^2*c*x^2)^p/(%e^atanh(a*x)*x),x,6,-a*x*(c-a^2*c*x^2)^p*hypergeometric([1/2,1/2-p],[3/2],a^2*x^2)/(1-a^2*x^2)^p-(c-a^2*c*x^2)^p*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)*sqrt(1-a^2*x^2)/(1+2*p)],
[(c-a^2*c*x^2)^p/(%e^atanh(a*x)*x^2),x,6,-(c-a^2*c*x^2)^p*hypergeometric([-1/2,1/2-p],[1/2],a^2*x^2)/(x*(1-a^2*x^2)^p)+a*(c-a^2*c*x^2)^p*hypergeometric([1,1/2+p],[3/2+p],1-a^2*x^2)*sqrt(1-a^2*x^2)/(1+2*p)],

/* Integrands of the form x^m (c-a^2 c x^2)^p / E^(2 ArcTanh[a x]) */

/* Integrands of the form x^m E^(-2 ArcTanh[a x]) (c-a^2 c x^2)^p */

/* p>0 */
[(c-a^2*c*x^2)^4/%e^(2*atanh(a*x)),x,3,-4/3*c^4*(1-a*x)^6/a+12/7*c^4*(1-a*x)^7/a-3/4*c^4*(1-a*x)^8/a+1/9*c^4*(1-a*x)^9/a],
[(c-a^2*c*x^2)^3/%e^(2*atanh(a*x)),x,3,-4/5*c^3*(1-a*x)^5/a+2/3*c^3*(1-a*x)^6/a-1/7*c^3*(1-a*x)^7/a],
[(c-a^2*c*x^2)^2/%e^(2*atanh(a*x)),x,3,-1/2*c^2*(1-a*x)^4/a+1/5*c^2*(1-a*x)^5/a],
[(c-a^2*c*x^2)/%e^(2*atanh(a*x)),x,2,-1/3*c*(1-a*x)^3/a],

/* p<0 */
[1/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)),x,2,(-1)/(a*c*(1+a*x))],
[1/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)^2),x,4,(-1/4)/(a*c^2*(1+a*x)^2)+(-1/4)/(a*c^2*(1+a*x))+1/4*atanh(a*x)/(a*c^2)],
[1/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)^3),x,4,1/16/(a*c^3*(1-a*x))+(-1/12)/(a*c^3*(1+a*x)^3)+(-1/8)/(a*c^3*(1+a*x)^2)+(-3/16)/(a*c^3*(1+a*x))+1/4*atanh(a*x)/(a*c^3)],
[1/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)^4),x,4,1/64/(a*c^4*(1-a*x)^2)+5/64/(a*c^4*(1-a*x))+(-1/32)/(a*c^4*(1+a*x)^4)+(-1/16)/(a*c^4*(1+a*x)^3)+(-3/32)/(a*c^4*(1+a*x)^2)+(-5/32)/(a*c^4*(1+a*x))+15/64*atanh(a*x)/(a*c^4)],

/* Integrands of the form x^m E^(-2 ArcTanh[a x]) (c-a^2 c x^2)^(p/2) */

/* p>0 */
[x^3*(c-a^2*c*x^2)^(1/2)/%e^(2*atanh(a*x)),x,7,-3/4*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)/a^4-3/5*x^2*sqrt(c-a^2*c*x^2)/a^2+1/2*x^3*sqrt(c-a^2*c*x^2)/a-1/5*x^4*sqrt(c-a^2*c*x^2)-3/20*(8-5*a*x)*sqrt(c-a^2*c*x^2)/a^4],
[x^2*(c-a^2*c*x^2)^(1/2)/%e^(2*atanh(a*x)),x,6,7/8*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)/a^3+2/3*x^2*sqrt(c-a^2*c*x^2)/a-1/4*x^3*sqrt(c-a^2*c*x^2)+1/24*(32-21*a*x)*sqrt(c-a^2*c*x^2)/a^3],
[x*(c-a^2*c*x^2)^(1/2)/%e^(2*atanh(a*x)),x,5,-atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)/a^2-1/3*x^2*sqrt(c-a^2*c*x^2)-1/3*(5-3*a*x)*sqrt(c-a^2*c*x^2)/a^2],
[(c-a^2*c*x^2)^(1/2)/%e^(2*atanh(a*x)),x,5,3/2*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)/a+3/2*sqrt(c-a^2*c*x^2)/a+1/2*(1-a*x)*sqrt(c-a^2*c*x^2)/a],
[(c-a^2*c*x^2)^(1/2)/(%e^(2*atanh(a*x))*x),x,8,-2*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)-atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-sqrt(c-a^2*c*x^2)],
[(c-a^2*c*x^2)^(1/2)/(%e^(2*atanh(a*x))*x^2),x,8,a*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))*sqrt(c)+2*a*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-sqrt(c-a^2*c*x^2)/x],
[(c-a^2*c*x^2)^(1/2)/(%e^(2*atanh(a*x))*x^3),x,6,-3/2*a^2*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-1/2*sqrt(c-a^2*c*x^2)/x^2+2*a*sqrt(c-a^2*c*x^2)/x],
[(c-a^2*c*x^2)^(1/2)/(%e^(2*atanh(a*x))*x^4),x,7,a^3*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-1/3*sqrt(c-a^2*c*x^2)/x^3+a*sqrt(c-a^2*c*x^2)/x^2-5/3*a^2*sqrt(c-a^2*c*x^2)/x],
[(c-a^2*c*x^2)^(1/2)/(%e^(2*atanh(a*x))*x^5),x,8,-7/8*a^4*atanh(sqrt(c-a^2*c*x^2)/sqrt(c))*sqrt(c)-1/4*sqrt(c-a^2*c*x^2)/x^4+2/3*a*sqrt(c-a^2*c*x^2)/x^3-7/8*a^2*sqrt(c-a^2*c*x^2)/x^2+4/3*a^3*sqrt(c-a^2*c*x^2)/x],
[(c-a^2*c*x^2)^(3/2)/%e^(2*atanh(a*x)),x,6,5/12*(c-a^2*c*x^2)^(3/2)/a+1/4*(1-a*x)*(c-a^2*c*x^2)^(3/2)/a+5/8*c^(3/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a+5/8*c*x*sqrt(c-a^2*c*x^2)],
[(c-a^2*c*x^2)^(5/2)/%e^(2*atanh(a*x)),x,7,7/24*c*x*(c-a^2*c*x^2)^(3/2)+7/30*(c-a^2*c*x^2)^(5/2)/a+1/6*(1-a*x)*(c-a^2*c*x^2)^(5/2)/a+7/16*c^(5/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a+7/16*c^2*x*sqrt(c-a^2*c*x^2)],
[(c-a^2*c*x^2)^(7/2)/%e^(2*atanh(a*x)),x,8,15/64*c^2*x*(c-a^2*c*x^2)^(3/2)+3/16*c*x*(c-a^2*c*x^2)^(5/2)+9/56*(c-a^2*c*x^2)^(7/2)/a+1/8*(1-a*x)*(c-a^2*c*x^2)^(7/2)/a+45/128*c^(7/2)*atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/a+45/128*c^3*x*sqrt(c-a^2*c*x^2)],

/* p<0 */
[1/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(1/2)),x,4,-atan(a*x*sqrt(c)/sqrt(c-a^2*c*x^2))/(a*sqrt(c))-2*(1-a*x)/(a*sqrt(c-a^2*c*x^2))],
[1/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(3/2)),x,3,-2/3*(1-a*x)/(a*(c-a^2*c*x^2)^(3/2))+1/3*x/(c*sqrt(c-a^2*c*x^2))],
[1/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(5/2)),x,4,-2/5*(1-a*x)/(a*(c-a^2*c*x^2)^(5/2))+1/5*x/(c*(c-a^2*c*x^2)^(3/2))+2/5*x/(c^2*sqrt(c-a^2*c*x^2))],
[1/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)^(7/2)),x,5,-2/7*(1-a*x)/(a*(c-a^2*c*x^2)^(7/2))+1/7*x/(c*(c-a^2*c*x^2)^(5/2))+4/21*x/(c^2*(c-a^2*c*x^2)^(3/2))+8/21*x/(c^3*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^(-2 ArcTanh[a x]) (c-a^2 c x^2)^p with m symbolic */
[x^m*sqrt(c-a^2*c*x^2)/%e^(2*atanh(a*x)),x,7,c*(3+2*m)*x^(1+m)*hypergeometric([1/2,1/2*(1+m)],[1/2*(3+m)],a^2*x^2)*sqrt(1-a^2*x^2)/((1+m)*(2+m)*sqrt(c-a^2*c*x^2))-2*a*c*x^(2+m)*hypergeometric([1/2,1/2*(2+m)],[1/2*(4+m)],a^2*x^2)*sqrt(1-a^2*x^2)/((2+m)*sqrt(c-a^2*c*x^2))-x^(1+m)*sqrt(c-a^2*c*x^2)/(2+m)],

/* Integrands of the form x^m E^(-2 ArcTanh[a x]) (c-a^2 c x^2)^p with p symbolic */
[(c-a^2*c*x^2)^p/%e^(2*atanh(a*x)),x,3,2^(1+p)*(c-a^2*c*x^2)^p*hypergeometric([-1-p,p],[1+p],1/2*(1+a*x))/(a*p*(1-a*x)^p)],

/* Integrands of the form x^m (c-a^2 c x^2)^p / E^(3 ArcTanh[a x]) */

/* Integrands of the form x^m E^(-3 ArcTanh[a x]) (c-a^2 c x^2)^p */

/* p>0 */
[(c-a^2*c*x^2)^4/%e^(3*atanh(a*x)),x,8,55/192*c^4*x*(1-a^2*x^2)^(3/2)+11/48*c^4*x*(1-a^2*x^2)^(5/2)+11/56*c^4*(1-a^2*x^2)^(7/2)/a+11/72*c^4*(1-a*x)*(1-a^2*x^2)^(7/2)/a+1/9*c^4*(1-a*x)^2*(1-a^2*x^2)^(7/2)/a+55/128*c^4*asin(a*x)/a+55/128*c^4*x*sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^3/%e^(3*atanh(a*x)),x,7,3/8*c^3*x*(1-a^2*x^2)^(3/2)+3/10*c^3*(1-a^2*x^2)^(5/2)/a+3/14*c^3*(1-a*x)*(1-a^2*x^2)^(5/2)/a+1/7*c^3*(1-a*x)^2*(1-a^2*x^2)^(5/2)/a+9/16*c^3*asin(a*x)/a+9/16*c^3*x*sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^2/%e^(3*atanh(a*x)),x,6,7/12*c^2*(1-a^2*x^2)^(3/2)/a+7/20*c^2*(1-a*x)*(1-a^2*x^2)^(3/2)/a+1/5*c^2*(1-a*x)^2*(1-a^2*x^2)^(3/2)/a+7/8*c^2*asin(a*x)/a+7/8*c^2*x*sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)/%e^(3*atanh(a*x)),x,5,5/2*c*asin(a*x)/a+5/2*c*sqrt(1-a^2*x^2)/a+5/6*c*(1-a*x)*sqrt(1-a^2*x^2)/a+1/3*c*(1-a*x)^2*sqrt(1-a^2*x^2)/a],

/* p<0 */
[1/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)),x,1,(-1/3)/(%e^(3*atanh(a*x))*a*c)],
[1/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)^2),x,5,-1/5*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x)^3)-2/15*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x)^2)-2/15*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x))],
[1/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)^3),x,6,8/35*x/(c^3*sqrt(1-a^2*x^2))+(-1/7)/(a*c^3*(1+a*x)^3*sqrt(1-a^2*x^2))+(-4/35)/(a*c^3*(1+a*x)^2*sqrt(1-a^2*x^2))+(-4/35)/(a*c^3*(1+a*x)*sqrt(1-a^2*x^2))],
[1/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)^4),x,7,8/63*x/(c^4*(1-a^2*x^2)^(3/2))+(-1/9)/(a*c^4*(1+a*x)^3*(1-a^2*x^2)^(3/2))+(-2/21)/(a*c^4*(1+a*x)^2*(1-a^2*x^2)^(3/2))+(-2/21)/(a*c^4*(1+a*x)*(1-a^2*x^2)^(3/2))+16/63*x/(c^4*sqrt(1-a^2*x^2))],

/* Integrands of the form x^m E^(-3 ArcTanh[a x]) (c-a^2 c x^2)^(p/2) */

/* p>0 */
[x^3*(c-a^2*c*x^2)^(1/2)/%e^(3*atanh(a*x)),x,4,4*x*sqrt(c-a^2*c*x^2)/(a^3*sqrt(1-a^2*x^2))-2*x^2*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))+4/3*x^3*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-3/4*x^4*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+1/5*a*x^5*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*log(1+a*x)*sqrt(c-a^2*c*x^2)/(a^4*sqrt(1-a^2*x^2))],
[x^2*(c-a^2*c*x^2)^(1/2)/%e^(3*atanh(a*x)),x,4,-4*x*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))+2*x^2*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-x^3*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+1/4*a*x^4*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+4*log(1+a*x)*sqrt(c-a^2*c*x^2)/(a^3*sqrt(1-a^2*x^2))],
[x*(c-a^2*c*x^2)^(1/2)/%e^(3*atanh(a*x)),x,4,4*x*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-3/2*x^2*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+1/3*a*x^3*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*log(1+a*x)*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))],
[(c-a^2*c*x^2)^(1/2)/%e^(3*atanh(a*x)),x,4,-3*x*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+1/2*a*x^2*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+4*log(1+a*x)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[(c-a^2*c*x^2)^(1/2)/(%e^(3*atanh(a*x))*x),x,4,a*x*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*log(1+a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(1/2)/(%e^(3*atanh(a*x))*x^2),x,4,-sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))-3*a*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+4*a*log(1+a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(1/2)/(%e^(3*atanh(a*x))*x^3),x,4,-1/2*sqrt(c-a^2*c*x^2)/(x^2*sqrt(1-a^2*x^2))+3*a*sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))+4*a^2*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*a^2*log(1+a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(1/2)/(%e^(3*atanh(a*x))*x^4),x,4,-1/3*sqrt(c-a^2*c*x^2)/(x^3*sqrt(1-a^2*x^2))+3/2*a*sqrt(c-a^2*c*x^2)/(x^2*sqrt(1-a^2*x^2))-4*a^2*sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))-4*a^3*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)+4*a^3*log(1+a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(1/2)/(%e^(3*atanh(a*x))*x^5),x,4,-1/4*sqrt(c-a^2*c*x^2)/(x^4*sqrt(1-a^2*x^2))+a*sqrt(c-a^2*c*x^2)/(x^3*sqrt(1-a^2*x^2))-2*a^2*sqrt(c-a^2*c*x^2)/(x^2*sqrt(1-a^2*x^2))+4*a^3*sqrt(c-a^2*c*x^2)/(x*sqrt(1-a^2*x^2))+4*a^4*log(x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)-4*a^4*log(1+a*x)*sqrt(c-a^2*c*x^2)/sqrt(1-a^2*x^2)],
[(c-a^2*c*x^2)^(9/2)/%e^(3*atanh(a*x)),x,4,-8/7*c^4*(1-a*x)^7*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+3/2*c^4*(1-a*x)^8*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-2/3*c^4*(1-a*x)^9*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+1/10*c^4*(1-a*x)^10*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[(c-a^2*c*x^2)^(7/2)/%e^(3*atanh(a*x)),x,4,-2/3*c^3*(1-a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+4/7*c^3*(1-a*x)^7*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/8*c^3*(1-a*x)^8*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[(c-a^2*c*x^2)^(5/2)/%e^(3*atanh(a*x)),x,4,-2/5*c^2*(1-a*x)^5*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+1/6*c^2*(1-a*x)^6*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],
[(c-a^2*c*x^2)^(3/2)/%e^(3*atanh(a*x)),x,3,-1/4*c*(1-a*x)^4*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))],

/* p<0 */
[1/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(1/2)),x,4,-2*sqrt(1-a^2*x^2)/(a*(1+a*x)*sqrt(c-a^2*c*x^2))-log(1+a*x)*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))],
[1/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(3/2)),x,3,-1/2*sqrt(1-a^2*x^2)/(a*c*(1+a*x)^2*sqrt(c-a^2*c*x^2))],
[1/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(5/2)),x,5,-1/6*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x)^3*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x)^2*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a*c^2*(1+a*x)*sqrt(c-a^2*c*x^2))+1/8*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c^2*sqrt(c-a^2*c*x^2))],
[1/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(7/2)),x,5,1/32*sqrt(1-a^2*x^2)/(a*c^3*(1-a*x)*sqrt(c-a^2*c*x^2))-1/16*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)^4*sqrt(c-a^2*c*x^2))-1/12*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)^3*sqrt(c-a^2*c*x^2))-3/32*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)^2*sqrt(c-a^2*c*x^2))-1/8*sqrt(1-a^2*x^2)/(a*c^3*(1+a*x)*sqrt(c-a^2*c*x^2))+5/32*atanh(a*x)*sqrt(1-a^2*x^2)/(a*c^3*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^(-3 ArcTanh[a x]) (c-a^2 c x^2)^p with m symbolic */
[x^m*(c-a^2*c*x^2)^(1/2)/%e^(3*atanh(a*x)),x,5,-3*x^(1+m)*sqrt(c-a^2*c*x^2)/((1+m)*sqrt(1-a^2*x^2))+a*x^(2+m)*sqrt(c-a^2*c*x^2)/((2+m)*sqrt(1-a^2*x^2))+4*x^(1+m)*hypergeometric([1,1+m],[2+m],-a*x)*sqrt(c-a^2*c*x^2)/((1+m)*sqrt(1-a^2*x^2))],

/* Integrands of the form x^m E^(-3 ArcTanh[a x]) (c-a^2 c x^2)^p with p symbolic */
[(c-a^2*c*x^2)^p/%e^(3*atanh(a*x)),x,3,-2^(-1/2+p)*(1-a*x)^(5/2+p)*(c-a^2*c*x^2)^p*hypergeometric([3/2-p,5/2+p],[7/2+p],1/2*(1-a*x))/(a*(5+2*p)*(1-a^2*x^2)^p)],

/* Integrands of the form x^m (c-a^2 c x^2)^p E^(1/2 ArcTanh[a x]) */

/* Integrands of the form x^m E^(1/2 ArcTanh[a x]) (c-a^2 c x^2)^p */

/* Integrands of the form x^m E^(1/2 ArcTanh[a x]) (c-a^2 c x^2)^(p/2) */
[%e^(1/2*atanh(a*x))*(1-a^2*x^2)^(5/2),x,17,231/512*(1-a*x)^(1/4)*(1+a*x)^(3/4)/a+231/1280*(1-a*x)^(5/4)*(1+a*x)^(3/4)/a+77/960*(1-a*x)^(9/4)*(1+a*x)^(3/4)/a-77/480*(1-a*x)^(13/4)*(1+a*x)^(3/4)/a-11/60*(1-a*x)^(13/4)*(1+a*x)^(7/4)/a-1/6*(1-a*x)^(13/4)*(1+a*x)^(11/4)/a+231/512*atan(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))/(a*sqrt(2))-231/512*atan(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))/(a*sqrt(2))+231/1024*log(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))/(a*sqrt(2))-231/1024*log(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))/(a*sqrt(2))],
[%e^(1/2*atanh(a*x))*(1-a^2*x^2)^(3/2),x,15,35/64*(1-a*x)^(1/4)*(1+a*x)^(3/4)/a+7/32*(1-a*x)^(5/4)*(1+a*x)^(3/4)/a-7/24*(1-a*x)^(9/4)*(1+a*x)^(3/4)/a-1/4*(1-a*x)^(9/4)*(1+a*x)^(7/4)/a+35/64*atan(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))/(a*sqrt(2))-35/64*atan(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))/(a*sqrt(2))+35/128*log(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))/(a*sqrt(2))-35/128*log(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))/(a*sqrt(2))],
[%e^(1/2*atanh(a*x))*(1-a^2*x^2)^(1/2),x,13,3/4*(1-a*x)^(1/4)*(1+a*x)^(3/4)/a-1/2*(1-a*x)^(5/4)*(1+a*x)^(3/4)/a+3/4*atan(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))/(a*sqrt(2))-3/4*atan(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))/(a*sqrt(2))+3/8*log(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))/(a*sqrt(2))-3/8*log(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))/(a*sqrt(2))],
[%e^(1/2*atanh(a*x))/(1-a^2*x^2)^(1/2),x,11,log(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))/(a*sqrt(2))-log(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))/(a*sqrt(2))+atan(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(2)/a-atan(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(2)/a],
[%e^(1/2*atanh(a*x))/(1-a^2*x^2)^(3/2),x,1,-2/3*%e^(1/2*atanh(a*x))*(1-2*a*x)/(a*sqrt(1-a^2*x^2))],
[%e^(1/2*atanh(a*x))/(1-a^2*x^2)^(5/2),x,2,-2/35*%e^(1/2*atanh(a*x))*(1-6*a*x)/(a*(1-a^2*x^2)^(3/2))-16/35*%e^(1/2*atanh(a*x))*(1-2*a*x)/(a*sqrt(1-a^2*x^2))],
[%e^(1/2*atanh(a*x))/(1-a^2*x^2)^(7/2),x,3,-2/99*%e^(1/2*atanh(a*x))*(1-10*a*x)/(a*(1-a^2*x^2)^(5/2))-32/693*%e^(1/2*atanh(a*x))*(1-6*a*x)/(a*(1-a^2*x^2)^(3/2))-256/693*%e^(1/2*atanh(a*x))*(1-2*a*x)/(a*sqrt(1-a^2*x^2))],
[%e^(1/2*atanh(a*x))/(1-a^2*x^2)^(9/2),x,4,-2/195*%e^(1/2*atanh(a*x))*(1-14*a*x)/(a*(1-a^2*x^2)^(7/2))-112/6435*%e^(1/2*atanh(a*x))*(1-10*a*x)/(a*(1-a^2*x^2)^(5/2))-256/6435*%e^(1/2*atanh(a*x))*(1-6*a*x)/(a*(1-a^2*x^2)^(3/2))-2048/6435*%e^(1/2*atanh(a*x))*(1-2*a*x)/(a*sqrt(1-a^2*x^2))],
[%e^(1/2*atanh(a*x))*(c-a^2*c*x^2)^(5/2),x,18,231/512*c^2*(1-a*x)^(1/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+231/1280*c^2*(1-a*x)^(5/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+77/960*c^2*(1-a*x)^(9/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-77/480*c^2*(1-a*x)^(13/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-11/60*c^2*(1-a*x)^(13/4)*(1+a*x)^(7/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/6*c^2*(1-a*x)^(13/4)*(1+a*x)^(11/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+231/512*c^2*atan(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))-231/512*c^2*atan(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))+231/1024*c^2*log(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))-231/1024*c^2*log(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))],
[%e^(1/2*atanh(a*x))*(c-a^2*c*x^2)^(3/2),x,16,35/64*c*(1-a*x)^(1/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+7/32*c*(1-a*x)^(5/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-7/24*c*(1-a*x)^(9/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/4*c*(1-a*x)^(9/4)*(1+a*x)^(7/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+35/64*c*atan(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))-35/64*c*atan(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))+35/128*c*log(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))-35/128*c*log(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))],
[%e^(1/2*atanh(a*x))*(c-a^2*c*x^2)^(1/2),x,14,3/4*(1-a*x)^(1/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))-1/2*(1-a*x)^(5/4)*(1+a*x)^(3/4)*sqrt(c-a^2*c*x^2)/(a*sqrt(1-a^2*x^2))+3/4*atan(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))-3/4*atan(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))+3/8*log(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))-3/8*log(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))*sqrt(c-a^2*c*x^2)/(a*sqrt(2)*sqrt(1-a^2*x^2))],
[%e^(1/2*atanh(a*x))/(c-a^2*c*x^2)^(1/2),x,12,log(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))*sqrt(1-a^2*x^2)/(a*sqrt(2)*sqrt(c-a^2*c*x^2))-log(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4)+sqrt(1-a*x)/sqrt(1+a*x))*sqrt(1-a^2*x^2)/(a*sqrt(2)*sqrt(c-a^2*c*x^2))+atan(1-(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(2)*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))-atan(1+(1-a*x)^(1/4)*sqrt(2)/(1+a*x)^(1/4))*sqrt(2)*sqrt(1-a^2*x^2)/(a*sqrt(c-a^2*c*x^2))],
[%e^(1/2*atanh(a*x))/(c-a^2*c*x^2)^(3/2),x,1,-2/3*%e^(1/2*atanh(a*x))*(1-2*a*x)/(a*c*sqrt(c-a^2*c*x^2))],
[%e^(1/2*atanh(a*x))/(c-a^2*c*x^2)^(5/2),x,2,-2/35*%e^(1/2*atanh(a*x))*(1-6*a*x)/(a*c*(c-a^2*c*x^2)^(3/2))-16/35*%e^(1/2*atanh(a*x))*(1-2*a*x)/(a*c^2*sqrt(c-a^2*c*x^2))],
[%e^(1/2*atanh(a*x))/(c-a^2*c*x^2)^(7/2),x,3,-2/99*%e^(1/2*atanh(a*x))*(1-10*a*x)/(a*c*(c-a^2*c*x^2)^(5/2))-32/693*%e^(1/2*atanh(a*x))*(1-6*a*x)/(a*c^2*(c-a^2*c*x^2)^(3/2))-256/693*%e^(1/2*atanh(a*x))*(1-2*a*x)/(a*c^3*sqrt(c-a^2*c*x^2))],
[%e^(1/2*atanh(a*x))/(c-a^2*c*x^2)^(9/2),x,4,-2/195*%e^(1/2*atanh(a*x))*(1-14*a*x)/(a*c*(c-a^2*c*x^2)^(7/2))-112/6435*%e^(1/2*atanh(a*x))*(1-10*a*x)/(a*c^2*(c-a^2*c*x^2)^(5/2))-256/6435*%e^(1/2*atanh(a*x))*(1-6*a*x)/(a*c^3*(c-a^2*c*x^2)^(3/2))-2048/6435*%e^(1/2*atanh(a*x))*(1-2*a*x)/(a*c^4*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^(1/2 ArcTanh[a x]) (c-a^2 c x^2)^(p/4) */
[%e^(1/2*atanh(a*x))*x^3/(c-a^2*c*x^2)^(5/4),x,10,-2/3*(1-a*x)^(3/2)*(1-a^2*x^2)^(1/4)/(a^4*c*(c-a^2*c*x^2)^(1/4))+(1-a^2*x^2)^(1/4)*atanh(sqrt(1-a*x)/sqrt(2))/(a^4*c*(c-a^2*c*x^2)^(1/4)*sqrt(2))+(1-a^2*x^2)^(1/4)/(a^4*c*(c-a^2*c*x^2)^(1/4)*sqrt(1-a*x))+2*(1-a^2*x^2)^(1/4)*sqrt(1-a*x)/(a^4*c*(c-a^2*c*x^2)^(1/4))],
[%e^(1/2*atanh(a*x))*x^2/(c-a^2*c*x^2)^(5/4),x,8,-(1-a^2*x^2)^(1/4)*atanh(sqrt(1-a*x)/sqrt(2))/(a^3*c*(c-a^2*c*x^2)^(1/4)*sqrt(2))+(1-a^2*x^2)^(1/4)/(a^3*c*(c-a^2*c*x^2)^(1/4)*sqrt(1-a*x))+2*(1-a^2*x^2)^(1/4)*sqrt(1-a*x)/(a^3*c*(c-a^2*c*x^2)^(1/4))],
[%e^(1/2*atanh(a*x))*x/(c-a^2*c*x^2)^(5/4),x,5,(1-a^2*x^2)^(1/4)*atanh(sqrt(1-a*x)/sqrt(2))/(a^2*c*(c-a^2*c*x^2)^(1/4)*sqrt(2))+(1-a^2*x^2)^(1/4)/(a^2*c*(c-a^2*c*x^2)^(1/4)*sqrt(1-a*x))],
[%e^(1/2*atanh(a*x))/(c-a^2*c*x^2)^(5/4),x,5,-(1-a^2*x^2)^(1/4)*atanh(sqrt(1-a*x)/sqrt(2))/(a*c*(c-a^2*c*x^2)^(1/4)*sqrt(2))+(1-a^2*x^2)^(1/4)/(a*c*(c-a^2*c*x^2)^(1/4)*sqrt(1-a*x))],
[%e^(1/2*atanh(a*x))/(x*(c-a^2*c*x^2)^(5/4)),x,8,-2*(1-a^2*x^2)^(1/4)*atanh(sqrt(1-a*x))/(c*(c-a^2*c*x^2)^(1/4))+(1-a^2*x^2)^(1/4)*atanh(sqrt(1-a*x)/sqrt(2))/(c*(c-a^2*c*x^2)^(1/4)*sqrt(2))+(1-a^2*x^2)^(1/4)/(c*(c-a^2*c*x^2)^(1/4)*sqrt(1-a*x))],
[%e^(1/2*atanh(a*x))/(x^2*(c-a^2*c*x^2)^(5/4)),x,9,-a*(1-a^2*x^2)^(1/4)*atanh(sqrt(1-a*x))/(c*(c-a^2*c*x^2)^(1/4))-a*(1-a^2*x^2)^(1/4)*atanh(sqrt(1-a*x)/sqrt(2))/(c*(c-a^2*c*x^2)^(1/4)*sqrt(2))+2*a*(1-a^2*x^2)^(1/4)/(c*(c-a^2*c*x^2)^(1/4)*sqrt(1-a*x))-(1-a^2*x^2)^(1/4)/(c*x*(c-a^2*c*x^2)^(1/4)*sqrt(1-a*x))],

/* Integrands of the form x^m E^(1/2 ArcTanh[a x]) (c-a^2 c x^2)^(p/8) */
[%e^(1/2*atanh(a*x))*x^3/(c-a^2*c*x^2)^(9/8),x,5,-4/7*x^2*(1+a*x)^(1/8)*(1-a^2*x^2)^(1/8)/(a^2*c*(1-a*x)^(3/8)*(c-a^2*c*x^2)^(1/8))+8/21*(6-a*x)*(1+a*x)^(1/8)*(1-a^2*x^2)^(1/8)/(a^4*c*(1-a*x)^(3/8)*(c-a^2*c*x^2)^(1/8))+64/105*2^(1/8)*(1-a*x)^(5/8)*(1-a^2*x^2)^(1/8)*hypergeometric([5/8,7/8],[13/8],1/2*(1-a*x))/(a^4*c*(c-a^2*c*x^2)^(1/8))],
[%e^(1/2*atanh(a*x))*x^2/(c-a^2*c*x^2)^(9/8),x,1,4/3*%e^(1/2*atanh(a*x))*(2-a*x)/(a^3*c*(c-a^2*c*x^2)^(1/8))],
[%e^(1/2*atanh(a*x))*x/(c-a^2*c*x^2)^(9/8),x,4,4/3*(1+a*x)^(1/8)*(1-a^2*x^2)^(1/8)/(a^2*c*(1-a*x)^(3/8)*(c-a^2*c*x^2)^(1/8))+8/15*2^(1/8)*(1-a*x)^(5/8)*(1-a^2*x^2)^(1/8)*hypergeometric([5/8,7/8],[13/8],1/2*(1-a*x))/(a^2*c*(c-a^2*c*x^2)^(1/8))],
[%e^(1/2*atanh(a*x))/(c-a^2*c*x^2)^(9/8),x,3,4/3*2^(1/8)*(1-a^2*x^2)^(1/8)*hypergeometric([-3/8,7/8],[5/8],1/2*(1-a*x))/(a*c*(1-a*x)^(3/8)*(c-a^2*c*x^2)^(1/8))],
[%e^(1/2*atanh(a*x))/(x*(c-a^2*c*x^2)^(9/8)),x,3,-2*2^(5/8)*(1+a*x)^(1/8)*(1-a^2*x^2)^(1/8)*AppellF1(1/8,11/8,1,9/8,1/2*(1+a*x),1+a*x)/(c*(c-a^2*c*x^2)^(1/8))],

/* Integrands of the form x^m E^(1/2 ArcTanh[a x]) (c-a^2 c x^2)^p with p symbolic */

/* Integrands of the form x^m (c-a^2 c x^2)^p E^(n ArcTanh[a x]) */

/* Integrands of the form x^m E^(n ArcTanh[a x]) (c-a^2 c x^2)^p */

/* p>0 */
[%e^(n*atanh(a*x))*(c-a^2*c*x^2),x,2,-2^(2+1/2*n)*c*(1-a*x)^(2-1/2*n)*hypergeometric([-1-1/2*n,2-1/2*n],[3-1/2*n],1/2*(1-a*x))/(a*(4-n))],
[%e^(n*atanh(a*x))*(c-a^2*c*x^2)^2,x,2,-2^(3+1/2*n)*c^2*(1-a*x)^(3-1/2*n)*hypergeometric([-2-1/2*n,3-1/2*n],[4-1/2*n],1/2*(1-a*x))/(a*(6-n))],
[%e^(n*atanh(a*x))*(c-a^2*c*x^2)^3,x,2,-2^(4+1/2*n)*c^3*(1-a*x)^(4-1/2*n)*hypergeometric([-3-1/2*n,4-1/2*n],[5-1/2*n],1/2*(1-a*x))/(a*(8-n))],

/* p<0 */
[%e^(n*atanh(a*x))*x^4/(c-a^2*c*x^2),x,5,-1/6*n*x^2*(1+a*x)^(1/2*n)/(a^3*c*(1-a*x)^(1/2*n))-1/3*x^3*(1+a*x)^(1/2*n)/(a^2*c*(1-a*x)^(1/2*n))+1/6*(1+a*x)^(1/2*n)*(6+8*n+n^2+n^3-a*n*(6+n^2)*x)/(a^5*c*n*(1-a*x)^(1/2*n))+1/3*2^(-1+1/2*n)*n*(8+n^2)*(1-a*x)^(1-1/2*n)*hypergeometric([1-1/2*n,1-1/2*n],[2-1/2*n],1/2*(1-a*x))/(a^5*c*(2-n))],
[%e^(n*atanh(a*x))*x^3/(c-a^2*c*x^2),x,4,-1/2*x^2*(1+a*x)^(1/2*n)/(a^2*c*(1-a*x)^(1/2*n))+1/2*(1+a*x)^(1/2*n)*(2+n+n^2-a*n^2*x)/(a^4*c*n*(1-a*x)^(1/2*n))+2^(-1+1/2*n)*(2+n^2)*(1-a*x)^(1-1/2*n)*hypergeometric([1-1/2*n,1-1/2*n],[2-1/2*n],1/2*(1-a*x))/(a^4*c*(2-n))],
[%e^(n*atanh(a*x))*x^2/(c-a^2*c*x^2),x,4,%e^(n*atanh(a*x))/(a^3*c*n)+2^(1+1/2*n)*(1-a*x)^(1-1/2*n)*hypergeometric([1-1/2*n,-1/2*n],[2-1/2*n],1/2*(1-a*x))/(a^3*c*(2-n)),(1-n)*(1+a*x)^(1/2*n)/(a^3*c*n*(1-a*x)^(1/2*n))-x*(1+a*x)^(1/2*n)/(a^2*c*(1-a*x)^(1/2*n))+2^(1+1/2*n)*hypergeometric([-1/2*n,-1/2*n],[1-1/2*n],1/2*(1-a*x))/(a^3*c*(1-a*x)^(1/2*n))],
[%e^(n*atanh(a*x))*x/(c-a^2*c*x^2),x,3,-(1+a*x)^(1/2*n)/(a^2*c*n*(1-a*x)^(1/2*n))+2^(1+1/2*n)*hypergeometric([-1/2*n,-1/2*n],[1-1/2*n],1/2*(1-a*x))/(a^2*c*n*(1-a*x)^(1/2*n))],
[%e^(n*atanh(a*x))/(c-a^2*c*x^2),x,1,%e^(n*atanh(a*x))/(a*c*n)],
[%e^(n*atanh(a*x))/(x*(c-a^2*c*x^2)),x,3,(1+a*x)^(1/2*n)/(c*n*(1-a*x)^(1/2*n))-2*(1-a*x)^(1-1/2*n)*(1+a*x)^(1/2*(-2+n))*hypergeometric([1,1-1/2*n],[2-1/2*n],(1-a*x)/(1+a*x))/(c*(2-n))],
[%e^(n*atanh(a*x))/(x^2*(c-a^2*c*x^2)),x,5,a*(1+n)*(1+a*x)^(1/2*n)/(c*n*(1-a*x)^(1/2*n))-(1+a*x)^(1/2*n)/(c*x*(1-a*x)^(1/2*n))-2*a*n*(1-a*x)^(1-1/2*n)*(1+a*x)^(1/2*(-2+n))*hypergeometric([1,1-1/2*n],[2-1/2*n],(1-a*x)/(1+a*x))/(c*(2-n))],
[%e^(n*atanh(a*x))*x^4/(c-a^2*c*x^2)^2,x,10,(1-n)*(3+n)*(1-a*x)^(-1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(a^5*c^2*(2-n))+(3+n)*x*(1-a*x)^(-1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(a^4*c^2)-x^3*(1-a*x)^(-1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(a^2*c^2)+(1-a*x)^(1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(a^5*c^2*(2-n))-(1+a*x)^(1/2*(-2+n))/(a^5*c^2*(1-a*x)^(1/2*n))-(3+n)*(2-n^2)*(1-a*x)^(-1-1/2*n)*(1+a*x)^(1/2*n)/(a^5*c^2*(4-n^2))-(3+n)*(2-n^2)*(1+a*x)^(1/2*n)/(a^5*c^2*n*(4-n^2)*(1-a*x)^(1/2*n))-2^(1/2*n)*n*(1-a*x)^(1-1/2*n)*hypergeometric([1/2*(2-n),1-1/2*n],[2-1/2*n],1/2*(1-a*x))/(a^5*c^2*(2-n))],
[%e^(n*atanh(a*x))*x^3/(c-a^2*c*x^2)^2,x,10,-(1-a*x)^(1/2*(-2-n))*(1+a*x)^(1/2*(-2+n))/(a^4*c^2*(2+n))+2*(1-a*x)^(1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(a^4*c^2*n*(4-n^2))-2*(1+a*x)^(1/2*(-2+n))/(a^4*c^2*n*(2+n)*(1-a*x)^(1/2*n))+3*(1-a*x)^(1/2*(-2-n))*(1+a*x)^(1/2*n)/(a^4*c^2*(2+n))+3*(1+a*x)^(1/2*n)/(a^4*c^2*n*(2+n)*(1-a*x)^(1/2*n))-3*(1-a*x)^(1/2*(-2-n))*(1+a*x)^(1/2*(2+n))/(a^4*c^2*(2+n))+2^(2+1/2*n)*(1-a*x)^(1/2*(-2-n))*hypergeometric([1/2*(-2-n),-1-1/2*n],[-1/2*n],1/2*(1-a*x))/(a^4*c^2*(2+n))],
[%e^(n*atanh(a*x))*x^2/(c-a^2*c*x^2)^2,x,2,-%e^(n*atanh(a*x))*(2-n^2)/(a^3*c^2*n*(4-n^2))-%e^(n*atanh(a*x))*(n-2*a*x)/(a^3*c^2*(4-n^2)*(1-a^2*x^2))],
[%e^(n*atanh(a*x))*x/(c-a^2*c*x^2)^2,x,3,-%e^(n*atanh(a*x))/(a^2*c^2*(4-n^2))+%e^(n*atanh(a*x))*(2-a*n*x)/(a^2*c^2*(4-n^2)*(1-a^2*x^2)),-%e^(n*atanh(a*x))/(a^2*c^2*(4-n^2))+1/2*%e^(n*atanh(a*x))/(a^2*c^2*(1-a^2*x^2))+1/2*%e^(n*atanh(a*x))*n*(n-2*a*x)/(a^2*c^2*(4-n^2)*(1-a^2*x^2))],
[%e^(n*atanh(a*x))/(c-a^2*c*x^2)^2,x,2,2*%e^(n*atanh(a*x))/(a*c^2*n*(4-n^2))-%e^(n*atanh(a*x))*(n-2*a*x)/(a*c^2*(4-n^2)*(1-a^2*x^2))],
[%e^(n*atanh(a*x))/(x*(c-a^2*c*x^2)^2),x,6,(1-a*x)^(-1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(c^2*(2+n))-(4-n-n^2)*(1-a*x)^(1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(c^2*n*(4-n^2))+(4+n)*(1+a*x)^(1/2*(-2+n))/(c^2*n*(2+n)*(1-a*x)^(1/2*n))-2*(1-a*x)^(1-1/2*n)*(1+a*x)^(1/2*(-2+n))*hypergeometric([1,1-1/2*n],[2-1/2*n],(1-a*x)/(1+a*x))/(c^2*(2-n))],
[%e^(n*atanh(a*x))/(x^2*(c-a^2*c*x^2)^2),x,7,a*(3+n)*(1-a*x)^(-1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(c^2*(2+n))-(1-a*x)^(-1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(c^2*x)-a*(6+4*n-n^2-n^3)*(1-a*x)^(1-1/2*n)*(1+a*x)^(1/2*(-2+n))/(c^2*n*(4-n^2))+a*(6+4*n+n^2)*(1+a*x)^(1/2*(-2+n))/(c^2*n*(2+n)*(1-a*x)^(1/2*n))-2*a*n*(1-a*x)^(1-1/2*n)*(1+a*x)^(1/2*(-2+n))*hypergeometric([1,1-1/2*n],[2-1/2*n],(1-a*x)/(1+a*x))/(c^2*(2-n))],
[%e^(n*atanh(a*x))/(c-a^2*c*x^2)^3,x,3,24*%e^(n*atanh(a*x))/(a*c^3*n*(64-20*n^2+n^4))-%e^(n*atanh(a*x))*(n-4*a*x)/(a*c^3*(16-n^2)*(1-a^2*x^2)^2)-12*%e^(n*atanh(a*x))*(n-2*a*x)/(a*c^3*(4-n^2)*(16-n^2)*(1-a^2*x^2))],
[%e^(n*atanh(a*x))/(c-a^2*c*x^2)^4,x,4,720*%e^(n*atanh(a*x))/(a*c^4*n*(36-n^2)*(64-20*n^2+n^4))-%e^(n*atanh(a*x))*(n-6*a*x)/(a*c^4*(36-n^2)*(1-a^2*x^2)^3)-30*%e^(n*atanh(a*x))*(n-4*a*x)/(a*c^4*(16-n^2)*(36-n^2)*(1-a^2*x^2)^2)-360*%e^(n*atanh(a*x))*(n-2*a*x)/(a*c^4*(4-n^2)*(16-n^2)*(36-n^2)*(1-a^2*x^2))],

/* Integrands of the form x^m E^(n ArcTanh[a x]) (c-a^2 c x^2)^(p/2) */

/* p>0 */
[%e^(n*atanh(a*x))*x^3*sqrt(c-a^2*c*x^2),x,5,-1/5*x^2*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(3+n))*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))-1/60*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(3+n))*(8+n^2+3*a*n*x)*sqrt(c-a^2*c*x^2)/(a^4*sqrt(1-a^2*x^2))-1/15*2^(1/2*(-1+n))*n*(11+n^2)*(1-a*x)^(1/2*(3-n))*hypergeometric([1/2*(-1-n),1/2*(3-n)],[1/2*(5-n)],1/2*(1-a*x))*sqrt(c-a^2*c*x^2)/(a^4*(3-n)*sqrt(1-a^2*x^2))],
[%e^(n*atanh(a*x))*x^2*sqrt(c-a^2*c*x^2),x,5,-1/12*n*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(3+n))*sqrt(c-a^2*c*x^2)/(a^3*sqrt(1-a^2*x^2))-1/4*x*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(3+n))*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))-1/3*2^(1/2*(-1+n))*(3+n^2)*(1-a*x)^(1/2*(3-n))*hypergeometric([1/2*(-1-n),1/2*(3-n)],[1/2*(5-n)],1/2*(1-a*x))*sqrt(c-a^2*c*x^2)/(a^3*(3-n)*sqrt(1-a^2*x^2))],
[%e^(n*atanh(a*x))*x*sqrt(c-a^2*c*x^2),x,4,-1/3*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(3+n))*sqrt(c-a^2*c*x^2)/(a^2*sqrt(1-a^2*x^2))-1/3*2^(1/2*(3+n))*n*(1-a*x)^(1/2*(3-n))*hypergeometric([1/2*(-1-n),1/2*(3-n)],[1/2*(5-n)],1/2*(1-a*x))*sqrt(c-a^2*c*x^2)/(a^2*(3-n)*sqrt(1-a^2*x^2))],
[%e^(n*atanh(a*x))*sqrt(c-a^2*c*x^2),x,3,-2^(1/2*(3+n))*(1-a*x)^(1/2*(3-n))*hypergeometric([1/2*(-1-n),1/2*(3-n)],[1/2*(5-n)],1/2*(1-a*x))*sqrt(c-a^2*c*x^2)/(a*(3-n)*sqrt(1-a^2*x^2))],
[%e^(n*atanh(a*x))*sqrt(c-a^2*c*x^2)/x,x,7,2*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(1+n))*hypergeometric([1,1/2*(-1-n)],[1/2*(1-n)],(1-a*x)/(1+a*x))*sqrt(c-a^2*c*x^2)/((1+n)*sqrt(1-a^2*x^2))-2^(1/2*(3+n))*(1-a*x)^(1/2*(-1-n))*hypergeometric([1/2*(-1-n),1/2*(-1-n)],[1/2*(1-n)],1/2*(1-a*x))*sqrt(c-a^2*c*x^2)/((1+n)*sqrt(1-a^2*x^2))+2^(1/2*(3+n))*(1-a*x)^(1/2*(1-n))*hypergeometric([1/2*(-1-n),1/2*(1-n)],[1/2*(3-n)],1/2*(1-a*x))*sqrt(c-a^2*c*x^2)/((1-n)*sqrt(1-a^2*x^2))],
[%e^(n*atanh(a*x))*sqrt(c-a^2*c*x^2)/x^2,x,3,2^(3/2-1/2*n)*a*(1+a*x)^(1/2*(3+n))*AppellF1(1/2*(3+n),1/2*(-1+n),2,1/2*(5+n),1/2*(1+a*x),1+a*x)*sqrt(c-a^2*c*x^2)/((3+n)*sqrt(1-a^2*x^2))],
[%e^(n*atanh(a*x))*(c-a^2*c*x^2)^(3/2),x,3,-2^(1/2*(5+n))*c*(1-a*x)^(1/2*(5-n))*hypergeometric([1/2*(-3-n),1/2*(5-n)],[1/2*(7-n)],1/2*(1-a*x))*sqrt(c-a^2*c*x^2)/(a*(5-n)*sqrt(1-a^2*x^2))],

/* p<0 */
[%e^(n*atanh(a*x))*x^3/sqrt(c-a^2*c*x^2),x,5,-1/3*x^2*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(1+n))*sqrt(1-a^2*x^2)/(a^2*sqrt(c-a^2*c*x^2))-1/6*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(1+n))*(4+n+n^2+a*(1-n)*n*x)*sqrt(1-a^2*x^2)/(a^4*(1-n)*sqrt(c-a^2*c*x^2))-1/3*2^(1/2*(-1+n))*n*(5+n^2)*(1-a*x)^(1/2*(3-n))*hypergeometric([1/2*(1-n),1/2*(3-n)],[1/2*(5-n)],1/2*(1-a*x))*sqrt(1-a^2*x^2)/(a^4*(1-n)*(3-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))*x^2/sqrt(c-a^2*c*x^2),x,5,1/2*(1-n)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(1+n))*sqrt(1-a^2*x^2)/(a^3*(1+n)*sqrt(c-a^2*c*x^2))-1/2*x*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(1+n))*sqrt(1-a^2*x^2)/(a^2*sqrt(c-a^2*c*x^2))-2^(1/2*(1+n))*(1+n^2)*(1-a*x)^(1/2*(1-n))*hypergeometric([1/2*(-1-n),1/2*(1-n)],[1/2*(3-n)],1/2*(1-a*x))*sqrt(1-a^2*x^2)/(a^3*(1-n^2)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))*x/sqrt(c-a^2*c*x^2),x,4,-(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(1+n))*sqrt(1-a^2*x^2)/(a^2*(1+n)*sqrt(c-a^2*c*x^2))-2^(1/2*(3+n))*n*(1-a*x)^(1/2*(1-n))*hypergeometric([1/2*(-1-n),1/2*(1-n)],[1/2*(3-n)],1/2*(1-a*x))*sqrt(1-a^2*x^2)/(a^2*(1-n^2)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/sqrt(c-a^2*c*x^2),x,3,-2^(1/2*(1+n))*(1-a*x)^(1/2*(1-n))*hypergeometric([1/2*(1-n),1/2*(1-n)],[1/2*(3-n)],1/2*(1-a*x))*sqrt(1-a^2*x^2)/(a*(1-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x*sqrt(c-a^2*c*x^2)),x,3,-2*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-1+n))*hypergeometric([1,1/2*(1-n)],[1/2*(3-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/((1-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x^2*sqrt(c-a^2*c*x^2)),x,4,-(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(1+n))*sqrt(1-a^2*x^2)/(x*sqrt(c-a^2*c*x^2))-2*a*n*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-1+n))*hypergeometric([1,1/2*(1-n)],[1/2*(3-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/((1-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x^3*sqrt(c-a^2*c*x^2)),x,6,-1/2*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(1+n))*sqrt(1-a^2*x^2)/(x^2*sqrt(c-a^2*c*x^2))-1/2*a*n*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(1+n))*sqrt(1-a^2*x^2)/(x*sqrt(c-a^2*c*x^2))-a^2*(1+n^2)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-1+n))*hypergeometric([1,1/2*(1-n)],[1/2*(3-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/((1-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))*x^3/(c-a^2*c*x^2)^(3/2),x,5,-x^2*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(a^2*c*sqrt(c-a^2*c*x^2))+(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*(2+2*n+n^2-a*n*(3+2*n)*x)*sqrt(1-a^2*x^2)/(a^4*c*(1-n^2)*sqrt(c-a^2*c*x^2))-2^(1/2*(-1+n))*n*(1-a*x)^(1/2*(3-n))*hypergeometric([1/2*(3-n),1/2*(3-n)],[1/2*(5-n)],1/2*(1-a*x))*sqrt(1-a^2*x^2)/(a^4*c*(3-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))*x^2/(c-a^2*c*x^2)^(3/2),x,4,-%e^(n*atanh(a*x))*(n-a*x)/(a^3*c*(1-n^2)*sqrt(c-a^2*c*x^2))+2^(1/2*(1+n))*(1-a*x)^(1/2*(1-n))*hypergeometric([1/2*(1-n),1/2*(1-n)],[1/2*(3-n)],1/2*(1-a*x))*sqrt(1-a^2*x^2)/(a^3*c*(1-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))*x/(c-a^2*c*x^2)^(3/2),x,1,%e^(n*atanh(a*x))*(1-a*n*x)/(a^2*c*(1-n^2)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(c-a^2*c*x^2)^(3/2),x,1,-%e^(n*atanh(a*x))*(n-a*x)/(a*c*(1-n^2)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x*(c-a^2*c*x^2)^(3/2)),x,6,(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*(1+n)*sqrt(c-a^2*c*x^2))-(2+n)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*(1-n^2)*sqrt(c-a^2*c*x^2))-2*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*hypergeometric([1,1/2*(3-n)],[1/2*(5-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/(c*(3-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x^2*(c-a^2*c*x^2)^(3/2)),x,7,a*(2+n)*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*(1+n)*sqrt(c-a^2*c*x^2))-(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*x*sqrt(c-a^2*c*x^2))-a*(2+2*n+n^2)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*(1-n^2)*sqrt(c-a^2*c*x^2))-2*a*n*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*hypergeometric([1,1/2*(3-n)],[1/2*(5-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/(c*(3-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x^3*(c-a^2*c*x^2)^(3/2)),x,8,1/2*a^2*(3+2*n+n^2)*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*(1+n)*sqrt(c-a^2*c*x^2))-1/2*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*x^2*sqrt(c-a^2*c*x^2))-1/2*a*n*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*x*sqrt(c-a^2*c*x^2))-1/2*a^2*(6+5*n+2*n^2+n^3)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(c*(1-n^2)*sqrt(c-a^2*c*x^2))-a^2*(3+n^2)*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*hypergeometric([1,1/2*(3-n)],[1/2*(5-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/(c*(3-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))*x^3/(c-a^2*c*x^2)^(5/2),x,7,x^3*(1-a*x)^(1/2*(-3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(a*c^2*(3+n)*sqrt(c-a^2*c*x^2))-3*(2-n)*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(a^4*c^2*(9-n^2)*sqrt(c-a^2*c*x^2))-3*x*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(a^3*c^2*(3+n)*sqrt(c-a^2*c*x^2))+3*(1+2*n-n^2)*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(a^4*c^2*(3-n)*(1+n)*(3+n)*sqrt(c-a^2*c*x^2))-3*(1+2*n-n^2)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-1+n))*sqrt(1-a^2*x^2)/(a^4*c^2*(9-10*n^2+n^4)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))*x^2/(c-a^2*c*x^2)^(5/2),x,2,-%e^(n*atanh(a*x))*(n-3*a*x)/(a^3*c*(9-n^2)*(c-a^2*c*x^2)^(3/2))+%e^(n*atanh(a*x))*(3-n^2)*(n-a*x)/(a^3*c^2*(9-10*n^2+n^4)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))*x/(c-a^2*c*x^2)^(5/2),x,3,1/3*%e^(n*atanh(a*x))/(a^2*c*(c-a^2*c*x^2)^(3/2))+1/3*%e^(n*atanh(a*x))*n*(n-3*a*x)/(a^2*c*(9-n^2)*(c-a^2*c*x^2)^(3/2))+2*%e^(n*atanh(a*x))*n*(n-a*x)/(a^2*c^2*(9-10*n^2+n^4)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(c-a^2*c*x^2)^(5/2),x,2,-%e^(n*atanh(a*x))*(n-3*a*x)/(a*c*(9-n^2)*(c-a^2*c*x^2)^(3/2))-6*%e^(n*atanh(a*x))*(n-a*x)/(a*c^2*(1-n^2)*(9-n^2)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x*(c-a^2*c*x^2)^(5/2)),x,8,(1-a*x)^(1/2*(-3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(3+n)*sqrt(c-a^2*c*x^2))+(6+n)*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(1+n)*(3+n)*sqrt(c-a^2*c*x^2))-(15+6*n+n^2)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(3+n)*(1-n^2)*sqrt(c-a^2*c*x^2))+(18+7*n-2*n^2-n^3)*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(9-10*n^2+n^4)*sqrt(c-a^2*c*x^2))-2*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*hypergeometric([1,1/2*(3-n)],[1/2*(5-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/(c^2*(3-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x^2*(c-a^2*c*x^2)^(5/2)),x,9,a*(4+n)*(1-a*x)^(1/2*(-3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(3+n)*sqrt(c-a^2*c*x^2))-(1-a*x)^(1/2*(-3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*x*sqrt(c-a^2*c*x^2))+a*(12+6*n+n^2)*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(1+n)*(3+n)*sqrt(c-a^2*c*x^2))-a*(24+15*n+6*n^2+n^3)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(3+n)*(1-n^2)*sqrt(c-a^2*c*x^2))+a*(24+18*n+7*n^2-2*n^3-n^4)*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(9-10*n^2+n^4)*sqrt(c-a^2*c*x^2))-2*a*n*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*hypergeometric([1,1/2*(3-n)],[1/2*(5-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/(c^2*(3-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(x^3*(c-a^2*c*x^2)^(5/2)),x,10,1/2*a^2*(5+4*n+n^2)*(1-a*x)^(1/2*(-3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(3+n)*sqrt(c-a^2*c*x^2))-1/2*(1-a*x)^(1/2*(-3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*x^2*sqrt(c-a^2*c*x^2))-1/2*a*n*(1-a*x)^(1/2*(-3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*x*sqrt(c-a^2*c*x^2))+1/2*a^2*(30+17*n+6*n^2+n^3)*(1-a*x)^(1/2*(-1-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(1+n)*(3+n)*sqrt(c-a^2*c*x^2))-1/2*a^2*(75+54*n+20*n^2+6*n^3+n^4)*(1-a*x)^(1/2*(1-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(3+n)*(1-n^2)*sqrt(c-a^2*c*x^2))+1/2*a^2*(90+59*n+8*n^2+2*n^3-2*n^4-n^5)*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*sqrt(1-a^2*x^2)/(c^2*(9-10*n^2+n^4)*sqrt(c-a^2*c*x^2))-a^2*(5+n^2)*(1-a*x)^(1/2*(3-n))*(1+a*x)^(1/2*(-3+n))*hypergeometric([1,1/2*(3-n)],[1/2*(5-n)],(1-a*x)/(1+a*x))*sqrt(1-a^2*x^2)/(c^2*(3-n)*sqrt(c-a^2*c*x^2))],
[%e^(n*atanh(a*x))/(c-a^2*c*x^2)^(7/2),x,3,-%e^(n*atanh(a*x))*(n-5*a*x)/(a*c*(25-n^2)*(c-a^2*c*x^2)^(5/2))-20*%e^(n*atanh(a*x))*(n-3*a*x)/(a*c^2*(9-n^2)*(25-n^2)*(c-a^2*c*x^2)^(3/2))-120*%e^(n*atanh(a*x))*(n-a*x)/(a*c^3*(1-n^2)*(9-n^2)*(25-n^2)*sqrt(c-a^2*c*x^2))],

/* Integrands of the form x^m E^(n ArcTanh[a x]) (c-a^2 c x^2)^p with m symbolic */
[%e^(n*atanh(a*x))*x^m*(c-a^2*c*x^2)^2,x,2,c^2*x^(1+m)*AppellF1(1+m,1/2*(-4+n),-2-1/2*n,2+m,a*x,-a*x)/(1+m)],
[%e^(n*atanh(a*x))*x^m*(c-a^2*c*x^2),x,2,c*x^(1+m)*AppellF1(1+m,1/2*(-2+n),-1-1/2*n,2+m,a*x,-a*x)/(1+m)],
[%e^(n*atanh(a*x))*x^m/(c-a^2*c*x^2),x,2,x^(1+m)*AppellF1(1+m,1/2*(2+n),1-1/2*n,2+m,a*x,-a*x)/(c*(1+m))],
[%e^(n*atanh(a*x))*x^m/(c-a^2*c*x^2)^2,x,2,x^(1+m)*AppellF1(1+m,1/2*(4+n),2-1/2*n,2+m,a*x,-a*x)/(c^2*(1+m))],

/* Integrands of the form x^m E^(n ArcTanh[a x]) (c-a^2 c x^2)^p with p symbolic */
[%e^(n*atanh(a*x))*x^m*(c-a^2*c*x^2)^p,x,3,x^(1+m)*(c-a^2*c*x^2)^p*AppellF1(1+m,1/2*(n-2*p),-1/2*n-p,2+m,a*x,-a*x)/((1+m)*(1-a^2*x^2)^p)],
[%e^(n*atanh(a*x))*x*(c-a^2*c*x^2)^p,x,4,-1/2*(1-a*x)^(1-1/2*n+p)*(1+a*x)^(1+1/2*n+p)*(c-a^2*c*x^2)^p/(a^2*(1+p)*(1-a^2*x^2)^p)-2^(1/2*n+p)*n*(1-a*x)^(1-1/2*n+p)*(c-a^2*c*x^2)^p*hypergeometric([-1/2*n-p,1-1/2*n+p],[2-1/2*n+p],1/2*(1-a*x))/(a^2*(1+p)*(2-n+2*p)*(1-a^2*x^2)^p)],
[%e^(n*atanh(a*x))*(c-a^2*c*x^2)^p,x,3,-2^(1+1/2*n+p)*(1-a*x)^(1-1/2*n+p)*(c-a^2*c*x^2)^p*hypergeometric([-1/2*n-p,1-1/2*n+p],[2-1/2*n+p],1/2*(1-a*x))/(a*(2-n+2*p)*(1-a^2*x^2)^p)],
[%e^(2*(1+p)*atanh(a*x))/(1-a^2*x^2)^p,x,3,(1-a*x)^(1-2*p)/(a*(1-2*p))+1/(a*p*(1-a*x)^(2*p))],
[%e^(2*(1+p)*atanh(a*x))/(c-a^2*c*x^2)^p,x,4,(1-a*x)^(1-2*p)*(1-a^2*x^2)^p/(a*(1-2*p)*(c-a^2*c*x^2)^p)+(1-a^2*x^2)^p/(a*p*(1-a*x)^(2*p)*(c-a^2*c*x^2)^p)],
[%e^(2*p*atanh(a*x))*(c-a^2*c*x^2)^p,x,3,(1+a*x)^(1+2*p)*(c-a^2*c*x^2)^p/(a*(1+2*p)*(1-a^2*x^2)^p)],
[(c-a^2*c*x^2)^p/%e^(2*p*atanh(a*x)),x,3,-(1-a*x)^(1+2*p)*(c-a^2*c*x^2)^p/(a*(1+2*p)*(1-a^2*x^2)^p)],
[%e^(n*atanh(a*x))*x^2*(c-a^2*c*x^2)^(-1-1/2*n^2),x,1,%e^(n*atanh(a*x))*(1-a*n*x)/(a^3*c*n*(1-n^2)*(c-a^2*c*x^2)^(1/2*n^2))],
[%e^(6*atanh(a*x))*x^2/(c-a^2*c*x^2)^19,x,2,1/210*(-1+6*a*x)/(a^3*c^19*(1-a*x)^21*(1+a*x)^15)],
[%e^(4*atanh(a*x))*x^2/(c-a^2*c*x^2)^9,x,2,1/60*(-1+4*a*x)/(a^3*c^9*(1-a*x)^10*(1+a*x)^6)],
[%e^(2*atanh(a*x))*x^2/(c-a^2*c*x^2)^3,x,2,1/6*(-1+2*a*x)/(a^3*c^3*(1-a*x)^3*(1+a*x))],
[x^2/(%e^(2*atanh(a*x))*(c-a^2*c*x^2)^3),x,2,1/6*(1+2*a*x)/(a^3*c^3*(1-a*x)*(1+a*x)^3)],
[x^2/(%e^(4*atanh(a*x))*(c-a^2*c*x^2)^9),x,2,1/60*(1+4*a*x)/(a^3*c^9*(1-a*x)^6*(1+a*x)^10)],
[%e^(5*atanh(a*x))*x^2/(c-a^2*c*x^2)^(27/2),x,3,-1/120*(1-5*a*x)*sqrt(1-a^2*x^2)/(a^3*c^13*(1-a*x)^15*(1+a*x)^10*sqrt(c-a^2*c*x^2))],
[%e^(3*atanh(a*x))*x^2/(c-a^2*c*x^2)^(11/2),x,3,-1/24*(1-3*a*x)*sqrt(1-a^2*x^2)/(a^3*c^5*(1-a*x)^6*(1+a*x)^3*sqrt(c-a^2*c*x^2))],
[%e^atanh(a*x)*x^2/(c-a^2*c*x^2)^(3/2),x,4,1/2*sqrt(1-a^2*x^2)/(a^3*c*(1-a*x)*sqrt(c-a^2*c*x^2))+3/4*log(1-a*x)*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))+1/4*log(1+a*x)*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))],
[x^2/(%e^atanh(a*x)*(c-a^2*c*x^2)^(3/2)),x,4,-1/2*sqrt(1-a^2*x^2)/(a^3*c*(1+a*x)*sqrt(c-a^2*c*x^2))-1/4*log(1-a*x)*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))-3/4*log(1+a*x)*sqrt(1-a^2*x^2)/(a^3*c*sqrt(c-a^2*c*x^2))],
[x^2/(%e^(3*atanh(a*x))*(c-a^2*c*x^2)^(11/2)),x,3,1/24*(1+3*a*x)*sqrt(1-a^2*x^2)/(a^3*c^5*(1-a*x)^3*(1+a*x)^6*sqrt(c-a^2*c*x^2))],
[x^2/(%e^(5*atanh(a*x))*(c-a^2*c*x^2)^(27/2)),x,3,1/120*(1+5*a*x)*sqrt(1-a^2*x^2)/(a^3*c^13*(1-a*x)^10*(1+a*x)^15*sqrt(c-a^2*c*x^2))]]$
